### ISSUE TITLE
Feature request: style dots and corners

### ISSUE THREAD

**Issue by mortezakarimi** [endroid/qr-code#114]
If you can add more flexible feature to style qt such as this
![download](https://user-images.githubusercontent.com/4004087/27571512-86194728-5b1b-11e7-871b-b3af7eb1df10.png)
I am very grateful!‌ :grin:

**Comment by endroid** [comment]
Hi @mortezakarimi thank you. I will not add this myself but if someone is willing to contribute on this, that would be great.

**Comment by DASPRiD** [comment]
The new upstream QR code library supports that now.

**Comment by MelchiorKokernoot** [comment]
@DASPRiD What do you mean by "The new upstream QR code library"?

**Comment by DASPRiD** [comment]
> @DASPRiD What do you mean by "The new upstream QR code library"?

BaconQRCode, which this library is using.

**Comment by MelchiorKokernoot** [comment]
@DASPRiD Do you by any chance have a reference where I can learn how to do so?
I can't seem to find anything about changing the style.

**Comment by MelchiorKokernoot** [comment]
@DASPRiD Do you by any chance have a reference where I can learn how to do so?
I can't seem to find anything about changing the style.

**Comment by DASPRiD** [comment]
There's not really any documentation for this, but the ImageRenderer takes a RendererStyle object, which can be configured. Best to look at the source:

https://github.com/Bacon/BaconQrCode/blob/master/src/Renderer/ImageRenderer.php#L26
https://github.com/Bacon/BaconQrCode/blob/master/src/Renderer/RendererStyle/RendererStyle.php

**Comment by endroid** [comment]
Closed as this will not be implemented here.
