### ISSUE TITLE
Feature request: allow URL as Logo path

### ISSUE THREAD

**Issue by 287541828** [endroid/qr-code#118]
$qrCode->setLogo('http://www.xxx.com/xxx.png') ??? How can I use this?

```

    public function setLogo($logo)
    {
        if (!file_exists($logo)) {    // **How do I change it?**
            throw new DataDoesntExistsException("$logo file does not exist");
        }

        $this->logo = $logo;

        return $this;
    }
```

**Comment by endroid** [comment]
Hi, the file_exists method only checks local resources. You can use curl to check existence of remote resources.

Please note that not all output formats include the logo yet. I know the PNG writer does.

**Comment by 287541828** [comment]
Thank you very much~ Would you like to add such a feature later?

**Comment by endroid** [comment]
Yes I think that would be a useful improvement. I reopened the issue and assigned the corresponding labels. Anyone can contribute but when I have time I will implement this myself.

**Comment by huichen2017** [comment]
Can you add this function earlier?

**Comment by endroid** [comment]
This should be possible at the moment.
