### ISSUE TITLE
Can't install for Symfony 3.4

### ISSUE THREAD

**Issue by diriy** [endroid/qr-code#146]
The lib faces with problems with compatibility with Symfony 3.4. 

> $ composer require endroid/qr-code
Using version ^1.9 for endroid/qr-code
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>   Problem 1
    - The requested package symfony/symfony (locked at v3.2.14, required as 3.4.*) is satisfiable by symfony/symfony[v3.2.14] but these conflict with your requirements or minimum-stability.

> Installation failed, reverting ./composer.json to its original content.

**Comment by endroid** [comment]
Hi @diriy have you tried any of the latest versions? What message do you get when you require ^3.0 explicitly in your composer.json?

**Comment by diriy** [comment]
@endroid, I installed 3.1.1 implicitly through composer and that work fine. But when I install the way described in documentation (without specified version), I receive 1.9 and it is incompatible with Symfony 3.4. Could you please update the documentation?

**Comment by endroid** [comment]
When I install the library without explicitly specifying a version it installs the latest version here, so it looks like some issue with your configuraton, however that is still an assumption, given the fact that we did not find the cause yet. Anyway the library should always install the latest possible version possible so there is no use for updating the documentation to install a specific version.
