### ISSUE TITLE
Major quality decrease between versions 1.x and 3.x

### ISSUE THREAD

**Issue by szymach** [endroid/qr-code#147]
Hello,

I have been using the `endroid/qrcode` package in version `1.9.x` up until today and noticed it was abandoned, so I switched to the `qr-code` version (why the change, by the way?). I have also noticed that it has since been updated to version `3.x`, so I have decided to update all the way to it. I have immediately noticed that the images generated by the newer version are quite blurred (at least the ones encoded into base64). Is there any kind of quality parameter I have missed? I used the code almost exactly as it was given in the readme's example.

Cheers.

**Comment by endroid** [comment]
Hi @szymach thank you. Could you please post any of your code or at least describe how you generate the image so I can try to reproduce your issue? Also, does the image look blurred for all 3.x versions or after a specific hash or release? Maybe you can switch your writer to the DebugWriter to output all settings used during generation.

**Comment by szymach** [comment]
Hello, 

You can look at the example in the README of your project, I basically copied it line by line (aside from adding a label). The size was 150px, not 300px and I was encoding a base64 encoded sha512 hash code, different each time. I was using the latest version and have not tried previous from the `3.x` branch, since I moved directly from `1.9.x` to the newest. I will see if I have the time to output the debug result, since it was on a project I do at my work.

**Comment by endroid** [comment]
Hi @szymach I see this is caused by rounding. I have now added a method "setRoundBlockSize" which you can use to enable / disable block size rounding. By default it is set to true, so any PNG or other format will be rendered without interpolation. Hope this helps :)

**Comment by karakum** [comment]
Using `$qrCode->setRoundBlockSize(false);` do not work properly.
Dots size and holes size are different:

![default](https://user-images.githubusercontent.com/12033941/38481856-f3be1a08-3bf6-11e8-9911-a05c711e30f8.png)

**Comment by karakum** [comment]
Hi @endroid 
config:
```
endroid_qr_code:
    writer: 'png'
    size: 100
    margin: 0
    foreground_color: { r: 0, g: 0, b: 0 }
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: low
    encoding: UTF-8
    validate_result: false # checks if the result is readable
```
code:
```
        /** @var \Endroid\QrCode\Factory\QrCodeFactory $qrFactory */
        $qrFactory = $this->get('Endroid\QrCode\Factory\QrCodeFactory');

        /** @var QrCodeInterface $qrCode */
        $qrCode = $qrFactory->create('Dots size and holes size are different');
        $qrCode->setRoundBlockSize(false);

        return $qrCode->writeDataUri();
```

**Comment by endroid** [comment]
Hi @karakum I see what's causing the issue: when block sizes are not rounded no interpolation takes place. This results in the varying block sizes. In the latest version I made sure images are interpolated when only a part of a pixel is occupied.

Thank you!
