### ISSUE TITLE
Can't write PNG if no alpha is set for the colors

### ISSUE THREAD

**Issue by ahazebroucq** [endroid/qr-code#149]
Hi,

With `endroid/qr-code` v.3.2.1 it seems that we cannot use the `setForegroundColor()` method with a traditionnal RGB array : 
````php
$_qrCodeForegroundColor = array(
        'r' => 115,
        'g' => 103,
        'b' => 240
    );
$qrCode = new QrCode('Some text');
$qrCode->setForegroundColor($_qrCodeForegroundColor);
$qr = $qrCode->writeString()
````
 We get the following error :
````
Notice: Undefined index: a
````

Problem is solved by adding the requested `a` parameter. Maybe a default value should be used, or a more descriptive error message should be thrown. Or update the README to reflect this BC break.

Thanks !

**Comment by endroid** [comment]
Hi @ahazebroucq thank you. I now make sure the alpha value is added when it is not passed and tagged a new version. Hope that solves the issue.
