### ISSUE TITLE
Feature request: Better support for inline SVG

### ISSUE THREAD

**Issue by madflow** [endroid/qr-code#151]
It is already possible to render inline SVG by using the ```QrCode::writeString``` method.

However,  the "string" composed also includes the xml declaration, which is not needed by inline SVG:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg ...</svg>
```

1. It would be a great enhancement to be able to ommit the ```<?xml``` preamble, since it is not needed.
2. Add some css classes for styling.

**Comment by endroid** [comment]
Hi @madflow version 3.3 introduces writer options you can use to omit the header. The option you can use is exclude_xml_declaration (as described in the readme).
