### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Seanghai** [endroid/qr-code#153]
Hello there! I have a problem with this library.

When I use this library on mac os, it's work normally but when I use this library on ubuntu os, it display like:
An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected '?'

Filename: /var/www/html/projects/qr-code-project/vendor/endroid/qr-code/src/QrCode.php

Line Number: 168

Backtrace:

File: /var/www/html/projects/qr-code-project/vendor/composer/ClassLoader.php
Line: 322
Function: Composer\Autoload\includeFile

File: /var/www/html/projects/qr-code-project/application/controllers/Qr_code.php
Line: 66
Function: spl_autoload_call

File: /var/www/html/projects/qr-code-project/application/controllers/Qr_code.php
Line: 29
Function: encode_image

File: /var/www/html/projects/qr-code-project/index.php
Line: 308
Function: require_once

I use PHP 7.2.2 on ubuntu16.04
Please help me! Thank you in advance.

**Comment by endroid** [comment]
Hi @Seanghai looks like something is wrong with your environment as nullable return types are officially supported since PHP 7.1. I tested locally on ubuntu with PHP 7.2.2 and get no errors. Maybe you could try using a different PHP version and see if the problem persists.

**Comment by Seanghai** [comment]
Thank you. I see.
