### ISSUE TITLE
Please follow https://semver.org/

### ISSUE THREAD

**Issue by yannickl88** [endroid/qr-code#154]
In a recent commit (1) some functionaly was removed but the lib was not tagged as a Major version (or a Minor for that). After updating we ran the tests and a application it broke because of this.

I would ask that you follow semantic versioning more strictly or communicate BC breaks.

(1) Commits I am refering to:
 - https://github.com/endroid/qr-code/commit/09b694f26659981b339c7ced4b0683b8e79117fd (tagged with 3.2.4)
 - https://github.com/endroid/qr-code/commit/f9a2b9c14d862b563d81f5d8786255179848c26f (tagged with 3.2.5)

These remove some with functions and later remove the whole twig extension.

**Comment by yannickl88** [comment]
After looking deeper into this, your bundle is not yet compatible with the new version you created. This will cause it to break for people using it.

In the future I recommend bumping this with a MAJOR version (so 4.0.0) so you can update your bundle accordingly to support the new version and release a version there (preferably also a MAJOR version, but this can be MINOR or even a PATCH) which is compatible. This way you have no solvable set of versions which are not compatible with each other.

Now we have to add a conflict rule to our application for `3.2.3` or larger until you release a bundle version which works with your new patches.

**Comment by iltar** [comment]
The changes shouldn't have been removed in the minor version, the deprecation message clearly reflects this: `Using %s is deprecated as of 3.1 and will be removed in 4.0. Use %s::qrCodeDataUriFunction() instead.`

**Comment by endroid** [comment]
Hi @yannickl88 thank you for your feedback. I see I forgot to tag the bundle so I did now. I also made note of the BC breaks regarding the changes in the Twig extension. Thank you.

**Comment by yannickl88** [comment]
@endroid thanks! I still recommend being more careful with changes that removed functionality and not tagging them properly.
