### ISSUE TITLE
EPS files corrupted in german language environment

### ISSUE THREAD

**Issue by LinkingYou** [endroid/qr-code#156]
We have a german php environment (PHP7.2) with the following setting in php.ini:
`intl.default_locale = de`

Now the EPS files created with some errors.

In environment **without** the german settings the EPS started with ...
```
%!PS-Adobe-3.0 EPSF-3.0
%%BoundingBox: 0 0 320 320
/F { rectfill } def
2.55 2.55 2.55 setrgbcolor
0 0 320 320 F
0 0 0 setrgbcolor

```
In environment **with** the german settings this looks like:
```
%!PS-Adobe-3.0 EPSF-3.0
%%BoundingBox: 0 0 320 320
/F { rectfill } def
2,55 2,55 2,55 setrgbcolor
0 0 320 320 F
0 0 0 setrgbcolor
```
The problems are the decimal separators - so the EPS files are corrupted and can not opened by any graphic software.

**Comment by endroid** [comment]
Hi @LinkingYou I was unable to reproduce the issue, but I now use number_format to create the floats as string. Can you update to 3.2.8 and check if this solves the issue for you?

**Comment by LinkingYou** [comment]
Great work. It works perfect now. Thanks you the quick respond.
