### ISSUE TITLE
Missing writer for extension "gif"

### ISSUE THREAD

**Issue by xorgxx** [endroid/qr-code#157]
Hi, i discover this error this morning 
```
Uncaught PHP Exception Endroid\QrCode\Exception\UnsupportedExtensionException: "Missing writer for extension "gif"" 
```
i dont see where this come form. It's working very well and still, but some time i get this error.

Thank for helping
Sf3.3.16, QrcodeBundle 1.4

**Comment by endroid** [comment]
Hi @xorgxx are you sure you are using 1.4? The exception class you mention does not exist in that version.

**Comment by xorgxx** [comment]
Sorry version was endroid/qrcode": "2.4.0"

**Comment by endroid** [comment]
Ah ok. I see that version does not have a GIF writer, see https://github.com/endroid/qr-code/tree/2.4.0/src/Writer. So maybe you should use the .png extension in the URL you use to generate the image.

**Comment by xorgxx** [comment]
generate url in controller by `            $url        = $this->generateUrl( 'nfc_secure_index',array('machash' => $yneTag->getMachash()), UrlGeneratorInterface::ABSOLUTE_URL );
`
generate Qrcode in twig by : `<img src="{{ qrcode_url( url ) }}"/>`

**Comment by endroid** [comment]
I am not familiar with the 'nfc_secure_index' route, it is not part of this library. What URL does it generate? If it generates a URL ending with .gif you have the source of the issue.

**Comment by xorgxx** [comment]
this url pass to qrcode_url() : `https://www.xxxx.com/fr/qrcode/https://www.xxxx.com/fr/xxxx/nfctag/secure/7f3a37740896b0a9062ee1a8c8f4d204`

**Comment by endroid** [comment]
Hi @xorgxx when I search the code there is no presence of the string gif and when I check out the 2.4.0 version and use the qrcode_url twig call to render your URL, I get a normal PNG. In other words unfortunately I am not able to reproduce the issue you are having...

**Comment by endroid** [comment]
Maybe you could try to use a more recent version of the library or generate the code programmatically instead of via the Twig extension since it seems you're the only one having this issue.

**Comment by xorgxx** [comment]
This is why i was asking same help. I have look before. more over, it can be that for some raison the url to pass to qrcode_url()  suppose to have **no extension**  having extension.gif? then in my code i have some bug's. it das not always bug. I even think it das apen only same time with Iphone :/.

**Comment by xorgxx** [comment]
i also see now that this error come main ly with `googlebot(at)googlebot.com!! `
