### ISSUE TITLE
Composer will add  double version

### ISSUE THREAD

**Issue by PeterRock** [endroid/qr-code#159]
<img width="384" alt="qr-2 2x" src="https://user-images.githubusercontent.com/17565091/37755045-d4d49868-2dde-11e8-8abe-4a55c4f05580.png">
<img width="201" alt="qr-co2 2x" src="https://user-images.githubusercontent.com/17565091/37755081-f299484e-2dde-11e8-8b79-f37bb3178c4c.png">

**Comment by endroid** [comment]
Hi @PeterRock thank you. Unfortunately I am unable to reproduce the issue. Did you try clearing your composer cache or remove (entries from) your lock file?
