### ISSUE TITLE
Just getting malformed characters on render();

### ISSUE THREAD

**Issue by iantearle** [endroid/qr-code#16]
All I get when using this library is:

�PNG  IHDR����<�PLTE���U��~5IDATX�혱��0D)�H�<�F�G�(�e ��������rE�蹑�;Q�I���X��Y90��d����G0�t��� &n�O��际��H&�t+��  ��,p�o��-&������vDri��S<�e`t)j�Yl��D�R�x��x�U�2����e�X�p[��Q�}-C�ʫ ��ᕀXZV�0E����Ą���v(��3113>����ǜ�LD��ie3ʪ��ڵ��ql)���ՋE&���a���5�ʝ�dv������HC�9ʙ?� Kt5\��l0����W~%��F���෴�>�L��OO�i��E��IEND�B`�

What am I doing wrong? Am i missing a library? I'm not seeing any error messages...

**Comment by Mark-Brightcloud** [comment]
@endroid setting "Content-Type" header to "image/png" like so: header('Content-Type: image/png'); didn't work for me. Any new updated fix?

**Comment by endroid** [comment]
Hi @Mark-Brightcloud when I generate a PNG and set the content header to image/png (like you say you do) I get a valid image. Can you provide a test case that fails and add it to the test suite or provide the code sample that generates the QR code so I can see if I can reproduce it? If I can reproduce the issue on this side, I can probably find a solution.
