### ISSUE TITLE
Call to undefined method Endroid\QrCode\QrCode::setRoundBlockSize() 

### ISSUE THREAD

**Issue by robp2175** [endroid/qr-code#162]
I simply install via composer and tried the advanced code as is in the Readme

`composer require endroid/qr-code`

**Comment by endroid** [comment]
Hi @robp2175 what version did it install exactly?

**Comment by robp2175** [comment]
I simply ran the composer install as suggested in the Readme. According to composer.lock it installed 2.5.0, which appears to be quite old.


Also getting this 
Class 'Endroid\QrCode\Response\QrCodeResponse'

**Comment by robp2175** [comment]
I am still on php 5.6. Is composer installing an older version for this purpose. I did not see any specific  php requirements.

**Comment by robp2175** [comment]
So, it does indeed look like that was the issue. I upgraded to php7.2 and those errors went away. However, a new error has come up. I will open a new issue for it.
