### ISSUE TITLE
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in \QrCode.php on line 61

### ISSUE THREAD

**Issue by robp2175** [endroid/qr-code#163]
I simply install via composer and tried the advanced code as is in the Readme

Updated to PHP 7.2 after a couple of previous errors.

composer require endroid/qr-code

**Comment by endroid** [comment]
Looks like you are running your script in php < 7. Versions prior to php 7 expect a "string" class because the scalar type "string" does not yet exist.

**Comment by robp2175** [comment]
I have confirmed I am running and I am still getting that same error

[cid:image001.png@01D3E3B5.3AF66B90]

**Comment by endroid** [comment]
Hmm too bad. I have no idea why php 7 incorrectly interprets the scalar type hint as a class type hint. Maybe you can post your issue in a php discussion group as it is a language related issue and people there probably have more expertise on this.

**Comment by robp2175** [comment]
Actually, please ignore this for now with my apologies, I think my server might be giving me some issues and I don’t want to waste your time. I will come back to this once I work this out and the problem persists. Or I will update you and close the ticket. I appreciate your time.

**Comment by daveMad** [comment]
@robp2175 Have you figured this out yet? I'm also running on php 7.1 and i'm getting this error, too.
