### ISSUE TITLE
Class 'QrReader' not found

### ISSUE THREAD

**Issue by PouDuo** [endroid/qr-code#164]
vendor/endroid/qr-code/src/Writer/PngWriter.php
line 51:
$reader = new QrReader($string, QrReader::SOURCE_TYPE_BLOB);

"Class 'QrReader' not found"

**Comment by endroid** [comment]
Hi @PouDuo what version do you have installed exactly? Can you look at what namespace the PngWriter includes the QrReader from or try the latest version?

**Comment by PouDuo** [comment]
"endroid/qr-code": "^2.5",

**Comment by PouDuo** [comment]
the PngWriter namespace has included QrReader

**Comment by PouDuo** [comment]
$qrCode->setValidateResult(true);，show error “Class 'QrReader' not found”，if true change false it's right。but in my old project，I use like this true。the same version 2.5

**Comment by endroid** [comment]
@PouDuo I see what the issue is. That version requires ^1.0.2 of khanamiryan/qrcode-detector-decoder while that library had a BC breaking change in 1.0.3. You could try installing a version lower than 1.0.3 by explicitly requiring a lower version to fix this. Maybe I'll make a change to the 2.x branch later.

**Comment by endroid** [comment]
Sorry I meant bacon/bacon-qr-code

**Comment by Vormillion** [comment]
Hi,

It seems that something wrong is happening during composer require endroid/qrcode:^2.5
It should download version 2.5.1 but it's still downloading 2.5.0 but composer show endroid/qrcode -a shows 2.5.1 available.

**Comment by endroid** [comment]
Hi @Vormillion thank you. You can try to install while explicitly requiring 2.5.1 and see what the conflicting dependency or requirement is. It is possible that an older version has some unfixed issues but maybe you can try to install a version older than 2.5.0 if you can not upgrade to a later version.

However of course I would always recommend installing 3.x if possible. Good luck!
