### ISSUE TITLE
There is something wrong with my app . 

### ISSUE THREAD

**Issue by sxsdlxw** [endroid/qr-code#167]
[4] ErrorException in QrCode.php line 19
语法错误: unexpected '.', expecting ',' or ';'

the past code is :
`const LABEL_FONT_PATH_DEFAULT = __DIR__ . '/../assets/noto_sans.otf';`

and I changed it at last :
`const LABEL_FONT_PATH_DEFAULT = './../assets/noto_sans.otf';`

is that right ? help me , please !

**Comment by endroid** [comment]
Hi @sxsdlxw thank you for your question. Constant expression support was added in PHP 5.6.0 so it appears you are running the script in an older version.
