### ISSUE TITLE
Uncaught TypeError:

### ISSUE THREAD

**Issue by staiji** [endroid/qr-code#168]
- Installing endroid/installer (1.0.3): Loading from cache
PHP Fatal error:  Uncaught TypeError: Return value of Endroid\Installer\Installer::activate() must be an instance of Endroid\Installer\void, none returned in D:\phpStudy\WWW\app\mtx222\vendor\endroid\installer\src\Installer.php:36
Stack trace:
#0 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(236): Endroid\Installer\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Endroid\Installer\Installer))

**Comment by endroid** [comment]
Hi @staiji void return types were introduced in PHP 7.1. This warning indicates you are using an older version.
