### ISSUE TITLE
QR code is not readable by Zebra MC3200 Scanner

### ISSUE THREAD

**Issue by pelex** [endroid/qr-code#169]
QR codes generated by aferrandini/phpqrcode works perfect. QR codes generated by endroid/qr-code are not recognized by the imager of Zebra MC3200.
Valid QR code generated by aferrandini/phpqrcode:
![qr_ok](https://user-images.githubusercontent.com/3096505/42213862-3cf18fce-7eba-11e8-83ac-5c1b8f013ce4.png)
Unreadable QR code generated by endroid/qr-code:
![qr_nok](https://user-images.githubusercontent.com/3096505/42213887-4b57ca10-7eba-11e8-9786-1766474225ec.png)

**Comment by endroid** [comment]
Hi @pelex thank you. Can you please share your code so I can see if there is something wrong? I need to know the exact version you are using and settings like error correction, rounding of edges, explicit width / height settings etc. Then I can generate the codes here and see if something is wrong.

Thank you!

**Comment by pelex** [comment]
Hello @endroid. I created some test file for You:
https://gist.github.com/pelex/96a7a3d8918ed8be514e680bff7cacbd

You shoud see something like these:
![qrcode](https://user-images.githubusercontent.com/3096505/42816500-54563a0e-89cb-11e8-9997-720247dae98a.png)
On the left Endroid and on the right Afferandi.
You can see how i done them earlier and now.

Thank You for Your time!

**Comment by endroid** [comment]
Hi @pelex I ran your code and the QR codes generated by the endroid/qr-code library are readable by my Android barcode scanner and the built-in validator which you can activate using $qrCode->setValidateResult(true), even using low error correction level and different contents. In other words: I can not reproduce the issue you are having. The images look different from Afferandi but there appear to be no issues reading the contents of your examples, so I can not explain why your scanner would have any issues reading this code.

If you are having doubts about the generated QR codes or question why these differ with Afferandi maybe the developer of that library (https://github.com/Bacon/BaconQrCode) has an answer, but it looks like the matrix generated by that library is correct and readable. Or if that doesn't help maybe you can contact your scanner support.

Please let me know if you find the cause. Maybe it can help other users.

**Comment by bradkovach** [comment]
I am having this issue with Zebra scanners as well.  I am encoding as `UTF-8` and have passed `setValidateResult(true)` with no luck.

**Comment by rlanyi** [comment]
I just got a reply from Motorola (Zebra) technical support team and they confirmed that the Zebra DS4208 can't read the QR codes that are generated with this library. I can confirm that the newer model DS4308 can read them successfully. Unfortunately the DS4208 is no longer supported so it won't receive any firmware upgrades anymore.

With another Zebra models you can try to upgrade firmware with 123Scan software. Hope this helps someone.
