### ISSUE TITLE
set same margin get different margin use eps

### ISSUE THREAD

**Issue by yann0917** [endroid/qr-code#171]
`EpsWriter` set `size=300` and `margin=10` but get different inner_width and margin

![image](https://user-images.githubusercontent.com/25262709/43126918-b03c9a76-8f60-11e8-8b1b-7aea2498678b.png)

**Comment by endroid** [comment]
Hi @yann0917 it looks like you have "round_block_size" enabled, can you check this? The round_block_size setting makes sure that block sizes always result in an integer, which also means that the inner width will not always add up to the defined size. Disable this setting to avoid rounding.
