### ISSUE TITLE
Question : PHP 7.0 below still support ? 

### ISSUE THREAD

**Issue by afiqiqmal** [endroid/qr-code#172]
Is latest version still support under PHP 7.0 ? do i need to use version 3.x.x or 2.x.x ?

**Comment by endroid** [comment]
Hi @afiqiqmal the latest version does not support php 7.0. If you are unable to upgrade your version of php I hope one of the older releases still works. I am not sure as older versions are not actively maintained anymore.

**Comment by HelvinHan** [comment]
7.0 please

**Comment by endroid** [comment]
Hi @HelvinHan thank you for your question. As I pointed out above I will not support outdated PHP versions. If it is not possible to update to an actively maintained version (7.2 or 7.3) you should check if an older version works for you or create a fork that supports the older version.

Good luck!
