### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by itsmeashutosh43** [endroid/qr-code#175]
The following code gave the error 
```
`use Endroid\QrCode\QrCode;

$qrCode = new QrCode('Life is too short to be generating QR codes');`

```

`PHP Fatal error:  Uncaught Error: Class 'Endroid\\QrCode\\QrCode' not found in /var/www/html/index.php:9\nStack trace:\n#0 {main}\n  thrown in /var/www/html/index.php on line 9`

**Comment by endroid** [comment]
Hi @itsmeashutosh43 looks like your autoloader can not find the file. Please check if you correctly installed the endroid/qr-code package (it should be present in your composer.json) and you included the autoload file generated by composer.
