### ISSUE TITLE
Add support for symfony 3 and 4 for version ^2

### ISSUE THREAD

**Issue by francislavoie** [endroid/qr-code#182]
I'm using version 2.5.1 of the QR code lib, but I'm currently locked to PHP 7.0 for now. I can't use v3 of this lib because it requires PHP 7.1. Would it be possible to add support for Symfony v3 and v4 to your 2.x branch? I'm having conflicts with some new libs I want to use.

Thanks

**Comment by endroid** [comment]
Hi @francislavoie thank you for your question. Symfony 4.x requires PHP 7.1+ so given your 7.0 restriction I think there is no need to add support for that version in the 2.x branch. I updated the symfony/* requirements to allow SF 3.x in the QR 2.x branch locally but the included bundle requires too many changes to make it work (and of course that is one of the reasons QR 3.x of my library was created). In other words I think if you want to use the library you can better create a fork or upgrade your PHP version (even 7.0 security support ends next month so having this version active in production can be a real issue). Anyway, good luck!
