### ISSUE TITLE
Adding logo to svg give error

### ISSUE THREAD

**Issue by royanon** [endroid/qr-code#184]
# Bug Report

**Info**
Version:  3.8.4

**Describe the Bug**
Adding logo to svg give error of SimpleXMLElement::addAttribute() expects parameter 2 to be string, integer given

**Steps to Reproduce**
1. Generate with svg format
2. Add logo, e.g. addLogoPath with an png logo
3. setLogoSize

**Expected Behavior**
Should generate an SVG with logo normally.

**Additional Context**
endroid/qr-code/src/Writer/SvgWriter.php
line 95 to 98 convert int to string.

**Comment by endroid** [comment]
Hi @royanon thanks for noticing! I added a test and fixed the issue in 3.4.9.

**Comment by royanon** [comment]
Great!
