### ISSUE TITLE
BaconQrCode 2.0

### ISSUE THREAD

**Issue by Y0lk** [endroid/qr-code#185]
bacon/bacon-qr-code has been updated to version 2.0 a while ago. Just wondering if there are any plans to update to the new version.

**Comment by endroid** [comment]
Hi @Y0lk good point, I upgraded to the new version in 3.5.0.

**Comment by Y0lk** [comment]
Great, thanks!

**Comment by drifio** [comment]
Should probably note that the new call signature for setErrorCorrectionLevel breaks backwards compatibility. setErrorCorrectionLevel() now expects an ErrorCorrectionLevel object, not a string.

From:
`$qrCode->setErrorCorrectionLevel(ErrorCorrectionLevel::HIGH);`

To:
`$qrCode->setErrorCorrectionLevel(new ErrorCorrectionLevel(ErrorCorrectionLevel::HIGH));`

Fixed the problem for us.

**Comment by endroid** [comment]
Hi @drifio you're right this is a BC break. I updated the readme accordingly and I now I also added a note to the release mentinoing the BC break. Happy to see you managed to fix it ;)
