### ISSUE TITLE
Illuminate\Foundation\ComposerScripts::postAutoloadDump

### ISSUE THREAD

**Issue by huanghao9015** [endroid/qr-code#187]
Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception

                                                                                                                                 
  [ErrorException]                                                                                                               
  Use of undefined constant createUniqueCode - assumed 'createUniqueCode' (this will throw an Error in a future version of PHP)

**Comment by endroid** [comment]
Hi @huanghao9015 I can not reproduce this issue and it looks like it is something thrown from a different library or framework as my code does not contain these namespaces or the createUniqueCode method.
