### ISSUE TITLE
Feature request: Get size of one dot

### ISSUE THREAD

**Issue by RikudouSage** [endroid/qr-code#188]
Is it possible to get size of one dot of the QR code image? If not, could this be added?

**Comment by endroid** [comment]
Hi @RikudouSage thank you. I moved the calculation logic from the writer to the qr code object so now you can call $qrCode->getData() and retrieve an array with the number of blocks, the block size, inner size, outer size etc. Please upgrade to 3.5.2 to use this functionality.
