### ISSUE TITLE
The library throws an exception only with a specific string

### ISSUE THREAD

**Issue by sergiq** [endroid/qr-code#192]
The library thows an exception when I execute the code with a specific string and the setValidateResult is set to true and ErrorCorrectionLevel::LOW

`
try {
        $qrCode = new QrCode('TEST111000747');
        $qrCode->setSize(100);
        $qrCode->setWriterByName('png');
        $qrCode->setMargin(0);
        $qrCode->setEncoding('UTF-8');
        $qrCode->setErrorCorrectionLevel(new ErrorCorrectionLevel(ErrorCorrectionLevel::LOW));
        $qrCode->setValidateResult(true);
        return $qrCode->writeString();

    } catch (Exception $e) {
        return "The id does not work"; // $e has no messages
    }
`
Testing some features of our project I created 1000 incrementals codes, from  TEST1110001 to TEST1110001000, and the error appear only with "TEST111000747". If I change a "T" for  "t" or add any other char to the end or begining or anywhere, the code works properly

I'm running the code on PHP 7.2.14-1 and ubuntu18.04.1

**Comment by sergiq** [comment]
I saw that with ErrorCorrectionLevel::HIGH is failing too with the code TEST111000286 and TEST111000303

**Comment by endroid** [comment]
Hi @sergiq I created a phpunit test with the code you provided above and I get no errors. If you can provide a failing test case (you can change the one I created) I can see what is wrong. See https://travis-ci.org/endroid/qr-code/builds/494540499
