### ISSUE TITLE
missing Symfony\Component\HttpFoundation\Response dependence

### ISSUE THREAD

**Issue by xcorp1986** [endroid/qr-code#194]
I have install "endroid/qr-code": "^3.5",when I use QrCodeResponse,the code shows that Class 'Symfony\Component\HttpFoundation\Response' not found,and I found the composer.json in "endroid/qr-code" missing such dependence

**Comment by endroid** [comment]
Hi @xcorp1986 thank you. The reason it is not a composer.json requirement is that many people don't use the QrCodeResponse class or if they do have the bundle and symfony/http-foundation installed. I updated the class so it throws a clear exception when the someone tries to use the class without having the package installed and I added the package to the composer suggest section.
