### ISSUE TITLE
Remove green border from QRcode

### ISSUE THREAD

**Issue by rauldeheer** [endroid/qr-code#195]
I'm currently generating QRcodes with this package, but I'm unable to remove the green border which comes with every code. Is it possible to remove this from the QRcode?

**Comment by endroid** [comment]
Hi @rauldeheer I have not heard about anyone getting green borders around their QR codes. Can you provide some more information (and any screenshots illustrating the issue) so I can try to reproduce this?

**Comment by endroid** [comment]
Hi @rauldeheer closing this for now. If you have any input that helps reproduce the issue let me know and I will reopen it.
