### ISSUE TITLE
Method 'setPadding' not found in Endroid\QrCode\QrCode

### ISSUE THREAD

**Issue by SphCstrs1** [endroid/qr-code#197]
Hey,

I have an issue when trying to use setPadding and render.
![issueSetPaddingRender](https://user-images.githubusercontent.com/32540545/54680848-2e98cc80-4b0b-11e9-81bf-017fbd37165c.png)

It says: Method 'setPadding' not found in Endroid\QrCode\QrCode 
and the same for render

Does this have something to do with the versions? Following a tutorial from a couple years ago so maybe it's just outdated... Don't know how to solve it :\

Thanks

**Comment by endroid** [comment]
Hi @SphCstrs1 indeed looks like you are using an old version. You can read in the readme how to install and use the latest version. You find it here https://github.com/endroid/qr-code.
