### ISSUE TITLE
Fatal error: Uncaught TypeError: is_file() expects parameter 1 to be a valid path

### ISSUE THREAD

**Issue by daronrc0** [endroid/qr-code#198]
Fatal error: Uncaught TypeError: is_file() expects parameter 1 to be a valid path, boolean given in \\vendor\endroid\qr-code\src\QrCode.php:254 

Stack trace: 
#0
 \\vendor\endroid\qr-code\src\QrCode.php(254): is_file(false)

 #1
 \\vendor\endroid\qr-code\src\QrCode.php(223): Endroid\QrCode\QrCode->setLabelFontPath(false)

 #2 
\\qrcode.php(21): Endroid\QrCode\QrCode->setLabel('Scan the code', 16, '\\htdocs...', 'center') 

#3
 {main} thrown in \\vendor\endroid\qr-code\src\QrCode.php on line 254

**Comment by endroid** [comment]
Hi @daronrc0 I updated the code so the error message when providing an invalid path is more clear. Thank you.
