### ISSUE TITLE
PHP 7.2 required

### ISSUE THREAD

**Issue by stadskle** [endroid/qr-code#199]
You have a dependency on endroid-installer 1.1.4 that requires (in composer at least) PHP 7.2, which effectively causes qr-code to require 7.2 as well. The latest update broke the build process on my 7.1 installation.

Could you please either:
 Update composer to reflect the 7.2 depedency or downgrade the depdency on endoid-installer if you want to stay on 7.1.

**Comment by endroid** [comment]
Hi @stadskle thank you. If you look at the endroid/qr-code composer.json you can see that the library does not depend on endroid/installer 1.1.4 but on ^1.0.3, which requires PHP 7.1. Composer will only install 1.1.4 if the PHP version under which you run composer is >= 7.2 or if you have a platform requirements section in your composer.json that forces a PHP version >= 7.2. If both are not the case and composer still installs an incompatible version, please report the issue there.

**Comment by stadskle** [comment]
Ah, sorry my bad. I build my composer file on a 7.2 machine, and then ran install on the 7.1 system. Thanks for the quick reply.

**Comment by endroid** [comment]
Np, happy to hear you found the cause :)
