### ISSUE TITLE
Problem with Advanced Example

### ISSUE THREAD

**Issue by bendspoons** [endroid/qr-code#202]
When using the function

`$qrCode->setLogoSize(150, 150);`

i get an error that there is no function "setLogoSize". Looking into the code, there is indeed no such fucntion. I replaced it with setLogoWidth() which works. Maybe its an outdated example?!

Installed via composer directly

Btw: Awesome Library! Thanks!

**Comment by endroid** [comment]
Hi @bendspoons when I look at the current version I see the method is present, see https://github.com/endroid/qr-code/blob/3.6.0/src/QrCode.php so maybe you are using an older (and possibly inconsistently documented) version.
