### ISSUE TITLE
BC breaks

### ISSUE THREAD

**Issue by DaveData** [endroid/qr-code#204]
Hi @endroid thanks for this really useful lib.

One thing that we noticed was a BC break change after the last update (3.4.9 -> 3.5.0). It's mentioned in the release notes. Same for the other BC breaks before (3.2.4 -> 3.2.5, 2.3.4 -> 2.4.0).

I would have expected the major version number to be changed. Usually I don't check release notes when minor or patch numbers change (maybe I should?).

So that came a bit unexpected.

What do you think?

**Comment by endroid** [comment]
Hi @DaveData thank you. As pointed out in the readme I try to keep BC breaks within a major version to a minimum but when I have small potentially BC breaking change I do not always bump the major version, unless it is part of some larger refactoring / rewrite. I hope you can live with that ;)

Never trust a 3rd party lib. Always write your own tests for the features you implement that rely on one. Even libraries that have a BC promise can suffer from errors or conflict with your code.

**Comment by DaveData** [comment]
Thanks for your feedback.

As I don't agree with the BE break/versioning I totally agree with the rest ;)
