### ISSUE TITLE
想问一下 扫描枪扫了之后会在前面加上\000026?

### ISSUE THREAD

**Issue by pengdyzhou** [endroid/qr-code#205]
百度了很多，都说是编码问题，不知道问题出在哪里！

**Comment by pengdyzhou** [comment]
$qrCode->setEncoding('ISO-8859-1');

设置编码为这个，才恢复正常

**Comment by pengdyzhou** [comment]
但是又碰到大小写的问题了

**Comment by endroid** [comment]
Hi @pengdyzhou good you found out yourself :)

**Comment by littlexiang** [comment]
+1 fell into the same shit hole...

**Comment by zwidny** [comment]
\000026是二维码的ECI标识，表示这个二维码的内容是用UTF-8编码的；如果这个标识的值是\000029，则表示这个二维码的内容是用GB18030编码的。
ECI标识可在制作二维码时选择加入，不加入，如果选择不加入，则扫码时不会输出；如果选择了加入，则扫码时可输出，或不输出。

refs:

http://www.gzm1.com/ArticleDetail/d2a64eee-bdeb-425e-847b-8b90c3134820.html
