### ISSUE TITLE
qr code not displaying onto my html page, and not rendering in email

### ISSUE THREAD

**Issue by zhiyizha** [endroid/qr-code#206]
I used the following code to try generating the code onto the page and embed it into an email body:
the settings for the page is 
```
			`header('Content-Type: image/png');
			 require_once '/var/www/vendor/autoload.php';
			use PHPMailer\PHPMailer\PHPMailer;
			use PHPMailer\PHPMailer\Exception;
			use Endroid\QrCode\ErrorCorrectionLevel;
			use Endroid\QrCode\LabelAlignment;
			use Endroid\QrCode\QrCode;
			use Endroid\QrCode\Response\QrCodeResponse;`
```

im using php7.0.3 and qrcode 2.5.1

```
			// Create a basic QR code
				$qrCode = new QrCode('Life is too short to be generating QR codes');
				$qrCode->setSize(300);
				// Set advanced options
				$qrCode->setWriterByName('png');
				// Directly output the QR code
				header('Content-Type: '.$qrCode->getContentType());
				echo $qrCode->writeString();

				// Save it to a file
				$qrCode->writeFile(__DIR__.'/qrcode.png');

				// Create a response object
				$response = new QrCodeResponse($qrCode);

```
The qr code can be store and works fine with writeFile, but its complete black with one tiny sqare box in the middle on web page. In the email, i only get random strings

**Comment by endroid** [comment]
Hi @zhiyizha the black page with the tiny square is usually an indication the PNG data is invalid or an error occurred. What response do you get if you uncomment the header('Content-Type line (and make sure you have error reporting on)? I.e. use this in the beginning.

ini_set('display_errors', 1);
error_reporting(E_ALL);

//header('Content-Type: image/png');

**Comment by zhiyizha** [comment]
nothing's change after i commented out the header. Also, i don't see any error on the page, there are error when i mistype something, but nothing else.

**Comment by endroid** [comment]
Hi @zhiyizha I see you have another line: header('Content-Type: '.$qrCode->getContentType()); Maybe that is the reason you still don't see any errors.

**Comment by zhiyizha** [comment]
ok, i have uncommented the line, theres no long a black page, but i got a bunch of random strings like so:

`�PNG  IHDR@@B�2� IDATx��}{�]�u��c�G��!�Wl����� u�6R넠�%u���٤U�uҦҥR]���q�Jš�(�j���0%*5�66�?���c����?O�Yk͚5���9����j���|�fͬ�̞�w�Zk`����`�H�����10��cx��`�>�����10��cx��`�~��m���ڵkQK��6:`V�GFF��}��7��������nϙ3G�|ժU��������+V�Hf*a�ڵ�C���kr�A6�ZcL�ժ~���0W��S��W�v�Vx��j��γ2��LK�2�Z-���(���;�=p�rx�0�K�$<�C�/S�̆XZ�spH���6�m�y��Xk��X,3�wg�_zIO`$����̾h<�0z#0LϪ���f�3F���0��UA7�ip��Ѱ.	�Af�oZ�~�a��y�=5we��f�:�4f:���h���R溙y����a4���5`�9h��N�S�|f�Z�!N_��W �Hc���4f��G3Fo ] ;8�h�d���RJC�pTW�V���9��i�����~��i�����3�������'��,���,��2����L�Xx�;h�K˿�df��dF�%��2k$���t��(f:�ș��N�2����߹���K�Rw�y�o�)܀�ɀ�}��{�W({�������/�Z�*��-[���x\����/|`

**Comment by endroid** [comment]
Hi @zhiyizha you could try to turn on the validation using $qrCode->setValidateResult(true). If you don't get a validation exception you at least know the PNG data generated by the library is readable and represents a readable QR code and the problem lies elsewhere (i.e. incorrect headers / malformed output).

**Comment by mgarabedian** [comment]
I was having a similar issue, but turned out i was accidentally echoing a line break before writeString. view-source: in chrome helped me figure out this issue

**Comment by zhiyizha** [comment]
sorry for the late reply. 
I went through the code, but i dont have any echo before the write string, i have some in html with 
`<h1><?php echo "somestring" ?></h1>`
can that cause the issue?

**Comment by endroid** [comment]
Hi @zhiyizha did you manage to solve the issue on your side? If not, please provide a more detailed code example (best: a failing test case) or the exact error message you are getting so I can look into it.
