### ISSUE TITLE
 Uncaught TypeError: Return value of Endroid\Installer\Installer::activate()

### ISSUE THREAD

**Issue by webribs** [endroid/qr-code#209]
After deploying project on linux hosting. I was adding a new package using SSH access. 

I run command
`composer require PACKAGE_NAME`

I got this error: 

**Fatal error: Uncaught TypeError: Return value of Endroid\Installer\Installer::activate() must be an instance of /vendor/endroid/installer/src/Installer.php:37**

Even simple `composer` command isn't working. I'm getting the same error again and again. I can't add more packages.

PHP version: 7.1.3
Composer version: 1.7.2
![Screenshot_5](https://user-images.githubusercontent.com/10451770/63466379-979abc80-c47c-11e9-80f5-9a0981cfd442.png)

**Comment by endroid** [comment]
Hi @webribs looks like something is wrong with your PHP installation. PHP 7.1 should support void return types and only versions before 7.1 (or a corrupted version) should give this message. Make sure you execute the composer install command in PHP 7.1. I.e. sometimes people using Docker accidentally execute commands from outside the container in a different / incompatible PHP version.

Good luck!
