### ISSUE TITLE
qrcode image can't parse string, when i add a logo

### ISSUE THREAD

**Issue by guihouchang** [endroid/qr-code#216]
![image](https://user-images.githubusercontent.com/6902339/66989655-5844c100-f0f7-11e9-991d-756ac06696bb.png)

 ```
$qrCode = new QrCode(SHARE_URL . '?inviteCode=' . $userInfo->getInvitCode());
            $iconPath = $this->config->resource->commonDir . '/icon.png';
            $qrCode->setLogoPath($iconPath);
            $qrCode->setLogoSize(100, 100);
            $inviteCode = $userInfo->getInvitCode();
            util::mkdirs($qrCodeDir);
            $qrCode->setRoundBlockSize(true);
            $qrCode->setWriterOptions(['exclude_xml_declaration' => true]);
            $qrCode->writeFile($qrCodeDir . $inviteCode . '.png');
```

**Comment by guihouchang** [comment]
No exact error messages
I think the size of the logo is too large, covering the qr code

**Comment by endroid** [comment]
Ah ok, that is a possibility of course. If the logo is too big it will wreck your code ;) You can use the built-in validator to see if the QR code is readable and experiment with different error correction level / sizes, but in general adding a logo will make your code less readable.
