### ISSUE TITLE
Why is endroid/installer required here?

### ISSUE THREAD

**Issue by Seldaek** [endroid/qr-code#218]
From reading the blog post about the installer, I don't understand why it is needed to install this library. There is no .install and nothing in extra in composer.json.

If it indeed isn't needed, please remove the requirement.

**Comment by endroid** [comment]
Hi @Seldaek you're right, I didn't notice. Probably some remains of earlier work. I removed the dependency, thank you!

**Comment by Seldaek** [comment]
Great, thanks!

**Comment by Seldaek** [comment]
@endroid a related question if I may, it seems that bacon/bacon-qr-code which you depend on uses https://github.com/DASPRiD/Enum internally, and then you require myclabs/php-enum, so installing this project lands you two enum implementations. Not a huge deal but just thought I let you know, if you can consolidate it by using the same enum dependency that you already have in the transitive dependencies it'd be a little cleaner.

**Comment by endroid** [comment]
Looks like a good library but it forces me to rewrite my code too much and make BC breaking changes. Also it is much less supported, so I think I'll stay with myclabs for now. Maybe later.

**Comment by Seldaek** [comment]
Sure thing, just wanted to point it out :) Thanks for having a look.
