### ISSUE TITLE
qr code not displaying on my page

### ISSUE THREAD

**Issue by FarahBella** [endroid/qr-code#219]
I tried to generate QR code by entering a sentence but it only displayed a tiny little empty box on my page. 

This is the code:

**<?php

header("Content-Type: image/png");
require "vendor/autoload.php";

use Endroid\QRCode\QrCode;

$qrcode = new QrCode("And thanks for providing your continuous support");

echo $qrcode->writeString();
die();** 

I have tried the code to display the errors on my page as well but nothing's changed and i seem to not know what's wrong. Please help me figure out.

**Comment by endroid** [comment]
Hi @FarahBella if you comment the header line you should get more information.
