### ISSUE TITLE
What does "Endroid detected by all type" mean?

### ISSUE THREAD

**Issue by nimasdj** [endroid/qr-code#220]
When I try to install qrcode by composer, it says Endroid detected by all type. What this message mean?
With qrcode, I have plan to generate qr with bitly links I am using this package for bitly:
https://github.com/phplicengine/bitly

**Comment by endroid** [comment]
Hi @nimasdj the message means that no specific framework type (Symfony etc.) was detected. I think the message can be clearer so I will change it. Thank you and good luck creating your bitly service.

**Comment by nimasdj** [comment]
Why should it care if a framework is installed? Many people might want to use it standalone. I guess better to turn off this checking.

**Comment by endroid** [comment]
This is not relevant anymore, the installer was removed 12 days ago as there is no framework specific installation anymore. This was moved to the bundle where it is relevant.

The installer is a generic composer plugin and only installs relevant files when a framework is detected. In other cases it does nothing and you can disable it if you don't like autoconfiguration in your project.
