### ISSUE TITLE
Not available for Symfony 5.0.*

### ISSUE THREAD

**Issue by Unlik** [endroid/qr-code#226]
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - endroid/qr-code-bundle 3.3.4 requires symfony/framework-bundle ^3.4|^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - endroid/qr-code-bundle 3.3.3 requires symfony/framework-bundle ^3.4|^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - endroid/qr-code-bundle 3.3.2 requires symfony/framework-bundle ^3.4|^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - endroid/qr-code-bundle 3.3.1 requires symfony/framework-bundle ^3.4|^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - endroid/qr-code-bundle 3.3.0 requires symfony/framework-bundle ^3.4|^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - endroid/qr-code-bundle 3.3.4 requires symfony/framework-bundle ^3.4|^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - Installation request for endroid/qr-code-bundle ^3.3 -> satisfiable by endroid/qr-code-bundle[3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4].

**Comment by endroid** [comment]
Hi @Unlik I just released an updated version of the qr-code and qr-code-bundle libraries. I hope this fixes your issue :)
