### ISSUE TITLE
[DOCS] PHP version compatibility

### ISSUE THREAD

**Issue by Tilogorn** [endroid/qr-code#229]
Would you mind adding a PHP version compatibility information to your README?

I just pushed to production to notice that this library crashes on PHP 7.0 (yeah I know, EOL, but it's an external hoster ;-)).

**Comment by endroid** [comment]
Hi @Tilogorn modern packages specify their PHP requirements in their composer.json so you can always find the PHP requirement (>= 7.2 for this package) there.

**Comment by Tilogorn** [comment]
Thanks for clarifying!
