### ISSUE TITLE
GD extension is not a required dependency

### ISSUE THREAD

**Issue by ossinkine** [endroid/qr-code#230]
The library successfully works without GD extension.
This extension is needed if you use PngWriter to generate the QR code or if you use SvgWriter with logo option.
I don't use this cases but I can't install the library until install useless GD extension.
So I propose to put it to `suggest` section in composer.json instead of `required` one.

**Comment by endroid** [comment]
Hi @ossinkine thank you but I prefer to leave it in. You're correct that the extension is not strictly required as you can use other writers than the default one so I understand your question but I don't want the people who use the PNG writer (and most do) to run into errors on runtime so I prefer the somewhat too strict requirement.
