### ISSUE TITLE
Imagick support

### ISSUE THREAD

**Issue by sorenlyhne** [endroid/qr-code#233]
Is it or will it be possible to use Imagick in stead of GD? I see that BaconQrCode already has that ability?

Thanks!

**Comment by endroid** [comment]
Hi @sorenlyhne at the moment the PngWriter uses GD and there is no support for Imagick for generating PNG files. If your environment does not support GD, you could try extend the PngWriter and replace the imagecreate... etc. calls with Imagick equivalents. Good luck. Or else maybe you could better use the BaconQrCode library to generate your images if that one already supports it.

Whatever works for you, good luck!

**Comment by sorenlyhne** [comment]
Thank you for the response :)
