### ISSUE TITLE
I didn't see the existence of 'setLogo'

### ISSUE THREAD

**Issue by zhangchenglin** [endroid/qr-code#234]
Text via Google Translate

I just came into contact with this open source library and it feels very good. Thank you for your contribution.
I saw the ‘setLabel’ package was sorted out,
I didn't see the existence of 'setLogo', but I saw the unit test of 'testSetLogo'.
Is there any reason why ‘setLogo’ is not provided, or has it not been iterated out, or is there any problem?

**Comment by zhangchenglin** [comment]
Can you tell us what you want to do in the future?
development plan?

**Comment by endroid** [comment]
Hi @zhangchenglin thank you for your question. The QrCode class provides both the setLabel and setLogo methods. You can use them as described in the readme.

Regarding development: if you have wishes, please let me know. I constantly maintain the library and I am open to suggestions.
