### ISSUE TITLE
Change the hard dependency on reader to only a suggestion

### ISSUE THREAD

**Issue by mmarton** [endroid/qr-code#235]
Hi!

great lib.

1 suggestion:

This library has a disabled by default optional functionality to validate qr-odes.
Would you consider to move the hard coded dependency on khanamiryan/qrcode-detector-decoder to a composer suggestion?

this would be a bc break, but it would mean one less dependency.

regards

**Comment by endroid** [comment]
Hi @mmarton thank you for your question. If it had a lot of dependencies or a large footprint I would surely consider your suggestion, but for now I'd rather leave it in by default, even though not everyone will use it.
