### ISSUE TITLE
Lack of imagedestroy in PngWriter

### ISSUE THREAD

**Issue by eslym** [endroid/qr-code#237]
Lack of `imagedestroy()` might causing unexpected memory leak during a bulk image processing

**Comment by endroid** [comment]
Hi @eslym good point. I now use the imagedestroy method where possible.

**Comment by eslym** [comment]
great, but i am sure one more `imagedestroy()` is needed after [PngWriter.php Line 38](https://github.com/endroid/qr-code/blob/master/src/Writer/PngWriter.php#L38) :)

**Comment by endroid** [comment]
You'r right ;)
