### ISSUE TITLE
Malware detection

### ISSUE THREAD

**Issue by McSeem** [endroid/qr-code#240]
Hi, my question is about security. Filters whether the library is malware? For example, what happens if the source data contains malicious code? 
`$qrCode = new QrCode($data);`
Or do I still need to check the source data with other tools? How the `setText()` method works?

**Comment by endroid** [comment]
Hi @McSeem thank you for your question. The library only handles QR code generation and does not check the input (which you pass via the constructor or the setText method) for any conditions, so you would need a different library / tool for that.
