### ISSUE TITLE
Some suggestions :-)

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/qr-code#245]
* Shouldn't it be `svg` in README.md at `$qrCode->setWriterByName('png');`, since with `png` the following (a few lines further down) doesn't make sense - right? `$qrCode->setWriterOptions(['exclude_xml_declaration' => true]);`

* Add a full list of available writers (and maybe their options) to README.md

* What about using `const`s for the writer names, e.g. at https://github.com/endroid/qr-code/blob/master/src/Writer/SvgWriter.php#L150:
  `return self::WRITER_SVG;`

**Comment by endroid** [comment]
* Good point, I updated the documentation to make clear the option is for the SVG writer
* I added a line to sum up the output formats. The SVG writer was the only one with an option.
* In the next major I will use the class, i.e. PngWriter::class as this is more common practice.

**Comment by ThomasLandauer** [comment]
BTW: In README.md, the link to some QR Code (just above "Readability") is broken.

**Comment by endroid** [comment]
Yes I know it is a live URL, works most of the time ;)
