### ISSUE TITLE
Exception thrown if the logo url is an external url (not local path)

### ISSUE THREAD

**Issue by DizzyC** [endroid/qr-code#248]
A change from this commit: https://github.com/endroid/qr-code/commit/03c71a2c8ed5203bdbd24c60e5f8250b69a937b7 adds a BC breaking issue.

Adding `$mimeType = $this->getMimeType($logoPath);` on the first line of the `PngWriter::addLogo()` method breakes for external logo paths since `getMimeType` uses `mime_content_type` to detect the mime type of a file and `mime_content_type` does apparently NOT work if the path to the file is an external path, only works for local paths.

So `mime_content_type("http://localhost/image.gif")` will fail with the error: `ErrorException: mimecontenttype(): Failed identify data 0:(null)`

This was working before this change.

See: https://github.com/endroid/qr-code/commit/03c71a2c8ed5203bdbd24c60e5f8250b69a937b7?diff=split#r38776582

**Comment by endroid** [comment]
Hi @DizzyC thank you. In the latest version I added mime type detection for URLs. Hope that helps!
