### ISSUE TITLE
EPS writer broken

### ISSUE THREAD

**Issue by Lozik** [endroid/qr-code#250]
The EPS writer seems to be broken. Attached to this issue is a file (the first one) generated with the library and EPS writer (converted to PNG to be able to upload to github & ROTATED by 90°). The second file is also generated with this library but with the SVG writer (again, converted to PNG for github). The SVG writer has the same output as the PNG writer. Some readers will be able to read the first QR code, others will not (especially khanamiryan/qrcode-detector-decoder will not and throw a Checksum Exception).
Strangely, the EPS writer output does not have the same error correcting level. I don't know how this is possible, considering the libraries code.
No settings, except the writer have been changed between the two generations. I expected the QR codes to be identical.

Side note: it is also strange that the generated QR code is flipped by 90° (but if done correctly, this is not wrong).

![broken](https://user-images.githubusercontent.com/16655002/83526132-437e3780-a4e6-11ea-9a5d-3c559312966d.png)
![not-broken-svg](https://user-images.githubusercontent.com/16655002/83526141-46792800-a4e6-11ea-8779-998505d99701.png)

**Comment by endroid** [comment]
Hi @Lozik when I create a QR code for the string "test" and save it to different formats, I see you are right: the EPS is generated differently than the PNG and SVG: it contains exactly the same blocks but it is mirrored (upside down) so I think an axis is reversed somewhere. I will look into it.

**Comment by endroid** [comment]
This should now be fixed in 3.8.1

**Comment by Lozik** [comment]
Thanks a lot! Works like a charm now.

**Comment by BillyBrooks** [comment]
How I'm I supposed to scan if it's on this phone
