### ISSUE TITLE
QRCode does not appear in word documents

### ISSUE THREAD

**Issue by Skematografi** [endroid/qr-code#251]
I tried to use this library to insert a QRCode in the .doc extension document, in an experiment in the QRCode browser it was seen but after trying to download it, the QRCode extension did not appear. whether you can provide a solution to this problem. Thanks you.

**Comment by endroid** [comment]
Hi @Skematografi if the QR Code was generated successfully you can save it to file using the writeFile() method and include the resulting file in your document like you would with any image.
