### ISSUE TITLE
Add Label On SVG

### ISSUE THREAD

**Issue by uriafranko** [endroid/qr-code#257]
Hey guys,
This package is amazing
but when I try to output an SVG the label is disappearing 
there is an option to keep the label on an SVG?

**Comment by endroid** [comment]
Hi @uriafranko thank you. Unfortunately that feature is not implemented yet for the SVG writer. I will leave this one open, would be a useful addition for a future version.

**Comment by endroid** [comment]
Wow great ;)

**Comment by endroid** [comment]
I'm closing this ticket because of lack of input. However if anyone still wants to add this feature, feel free to reopen / make a PR.
