### ISSUE TITLE
Text format

### ISSUE THREAD

**Issue by montaserfzy** [endroid/qr-code#259]
Text format like new line, bold, colored text and list of items

**Comment by endroid** [comment]
Hi @wpinventory although your question is not related tot he text format feature proposed by montaserfzy, you can best consult the author of the underlying library that generates the QR code matrix (BaconQrCode). I see a question similar to yours here https://github.com/Bacon/BaconQrCode/issues/21. Maybe that answers your question.

And please note that my library contains a validator. If you use $qrCode->validateResult(true) the generation process will validate if the data read from the QR code corresponds to the string you put in.

Good luck!

**Comment by wpinventory** [comment]
@endroid 

Thank you for the reply.  Sorry for posting in this thread. Doh!  That article you shared on the Bacon repo is on point.
