### ISSUE TITLE
ERROR: The Fpdf writer requires FPDF as dependency but the class "\FPDF" couldn't be found. 

### ISSUE THREAD

**Issue by juneszh** [endroid/qr-code#261]
cannot create qrcode image when update to v3.9.0

**Comment by juneszh** [comment]
I have not need pdf and just run
`new \Endroid\QrCode\QrCode($url);`

**Comment by MaximilianKresse** [comment]
Sorry this is on me. I simply ignored the fact that all writer instances are always created. I created a pull request to fix this.
