### ISSUE TITLE
URL string?

### ISSUE THREAD

**Issue by onlinesid** [endroid/qr-code#266]
This is just a question, is there a property/option that should be set if the data is a URL or is it just a string, e.g.:

```
use Endroid\QrCode\QrCode;

$qrCode = new QrCode('https://github.com');

// do we need to set a flag/option/property to tell QR code reader that the string is a URL?

header('Content-Type: '.$qrCode->getContentType());
echo $qrCode->writeString();
```

**Comment by MelchiorKokernoot** [comment]
Does not seem like it. Google lens parses the url flawlessly if you put it in the first parameter for the constructor.

**Comment by endroid** [comment]
@onlinesid Indeed there is no way to indicate the contents represent a URL. Howevers, readers should be able to easily detect the content type.
