### ISSUE TITLE
It does't work

### ISSUE THREAD

**Issue by dimkiriakos** [endroid/qr-code#268]
Fatal error: Uncaught Error: Interface 'Endroid\QrCode\QrCodeInterface' not found in C:\xampp\htdocs\qrgen\vendor\endroid\qr-code\src\QrCode.php:19 Stack trace: #0 C:\xampp\htdocs\qrgen\index.php(3): require() #1 {main} thrown in C:\xampp\htdocs\qrgen\vendor\endroid\qr-code\src\QrCode.php on line 19

**Comment by endroid** [comment]
Hi @dimkiriakos looks like your autoloader is not set up correctly. Did you install the package using composer and include / require the autoloader? If not, please try that and see if it helps.
