### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by sprain** [endroid/qr-code#269]
It would be great to see early support of PHP 8. 
Is that a goal for v4 maybe, as I see this is a work in progress? Can we help somehow?

**Comment by endroid** [comment]
Hi @sprain in the new version I intend tot PHP 8 (as for all my other libraries). Also, the underlying library that creates the QR code matrix is almost PHP 8 ready (see https://github.com/Bacon/BaconQrCode/pull/74) so the next major can use that version. I don't think any help is needed at the moment, it just takes some time :)
