### ISSUE TITLE
Adding a label on top and on the bottom

### ISSUE THREAD

**Issue by NoxxieNl** [endroid/qr-code#274]
Hiya,

Currently as I see it cannot add a label on top of the qr code and one on the bottom.
Or am I missing something :-)?

**Comment by endroid** [comment]
Hi @NoxxieNl that is correct. Currently you can only add a label to the bottom of the QR code ;)

**Comment by NoxxieNl** [comment]
You open for a pr if i can make it work to get a label on the top also?

**Comment by endroid** [comment]
@NoxxieNl I am working on a new major release, so I think it will be more efficiënt to add it to that version. Also, doing this in a clean way will probably break BC or force you to do some workarounds, but you are always free to make a PR.
