### ISSUE TITLE
Remove dependency on ext-gd

### ISSUE THREAD

**Issue by mallorydxw** [endroid/qr-code#275]
https://github.com/endroid/qr-code/blob/58d5872ca46b99b5c2e72cd2c8dea09ce2988156/composer.json#L14-L16

This module has `ext-gd` set as a requirement, however this module can be used without the GD extension being loaded by using the SVG writer instead of the default PNG writer (`$qrCode->setWriterByName('svg');`).

I just ran up against this issue when opening a PR where Travis was not loading the GD extension on some builds.

Thanks!

**Comment by endroid** [comment]
@mallorydxw Good point, I changed it. Thank you!
