### ISSUE TITLE
What is the unit of `size`?

### ISSUE THREAD

**Issue by jef348** [endroid/qr-code#277]
/**
     * @var int
     */
    protected $size = 300;

What does size mean? Is it in ciceros, didots, French picas, American picas, points, pixels, inches, meters, light years?

Without knowing what the number represents, it's hard to compute the right size to fit inside a fixed size area.

**Comment by endroid** [comment]
It's in kilojoule (kJ)

**Comment by jef348** [comment]
Here I was thinking I was going to get an answer that would make it easier to use this package.

I guess I can be thankful that it's not in gigawatts.
