### ISSUE TITLE
remove margin

### ISSUE THREAD

**Issue by pekineseZ** [endroid/qr-code#278]
Using the code below, I figered out I need to use **-18** to remove the margin nearly in full, isn't there an option to disable margin automatically?

Code:

```
$qrCode = new QrCode('Life is too short to be generating QR codes');
$qrCode->setSize(200);
$qrCode->setMargin(-18);
$qrCode->setWriterByName('png');
$qrCode->setEncoding('UTF-8');
$qrCode->setErrorCorrectionLevel(ErrorCorrectionLevel::HIGH());
$qrCode->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0, 'a' => 0]);
$qrCode->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255, 'a' => 0]);
```

It seems to be wrong to set margin to a negativ value to disable it?!

**Comment by endroid** [comment]
Hi @pekineseZ a margin is automatically because block sizes are rounded by default (to ensure a sharp and readable QR code). You can use the `setRoundBlockSize` method to disable rounding or to indicate the image should instead shrink or be enlarged.
