### ISSUE TITLE
Autoload not working

### ISSUE THREAD

**Issue by amostajo** [endroid/qr-code#281]
I have installed the package via composer and placed the exact code sample:

```php
use Endroid\QrCode\QrCode;
```

And then in the script:
```php
$qrCode = new QrCode($data);
header('Content-Type: '.$qrCode->getContentType());
echo $qrCode->writeString();
die;
```

Got this error in return:
```
Class 'Endroid\QrCode\QrCode' not found
```

Note, that composer is working well on my project, this is the only package that is presenting autoloading problems.

Regards.

**Comment by endroid** [comment]
Hi @amostajo can you post a complete example of your code, including your autoload statement? It should contain something like require dirname(__DIR__).'/vendor/autoload.php'; (can be somewhat different, depending on where your script resides).
