### ISSUE TITLE
Label enhancements

### ISSUE THREAD

**Issue by rolinger** [endroid/qr-code#286]
1) Is it possible to add a label to top of the the QR code.

IE:  `setLabelBottom` and `setLabelTop`

2) And then in each label, allow for text wrap based on size of image.  Currently, the label, if too many words, is centered and cuts off beginning and end words if produced image is to small.  As is, I can only get 4 words in a 256x256 image.

**Comment by endroid** [comment]
Hi @rolinger not possible at the moment but these would be useful improvements I think.

**Comment by hrvoj3e** [comment]
Maybe add all sides: top, bottom, left, right.

I could use label on the right rotated -90 degrees.

Something like
```php
setLabelPosition(LabelPosition::RIGHT)
setLabelRotation(LabelRotation::ROTATE_270)
```

**Comment by endroid** [comment]
Hi @hrvoj3e not something I will include but I think when implemented correctly this could be a nice addition so I'll leave it open as a possible enhancement. Regarding your question: labels can apply to different types of output but for now I think it is only implemented in SVG and PNG output. However the EPS writer for instance could be extended to include a label. And in your own custom writer you can do anything with the label and override default behavior.
