### ISSUE TITLE
PHP 8 - PngWriter throw a GenerateImageException

### ISSUE THREAD

**Issue by webdreamsCH** [endroid/qr-code#287]
Hi,
under PHP 8.0.0 the check is_resource($image) fails. 

until php 7.4. the type was resource(91) of type (gd)
under php 8 type is now a object GdImage

many thanks for the customization in source

**Comment by endroid** [comment]
Hi @webdreamsCH you're right. PHP 8.0 is not supported yet as one of the dependencies is not yet PHP 8 compatible. Subscribe to https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/103 if you want to know when support is added. As soon as this works I will update and tag.

**Comment by hrvoj3e** [comment]
Maybe add this note about PHP8 to readme?

**Comment by endroid** [comment]
In the new 4.0.0 version which is PHP 8.0 compatible both resource and GdImage are supported.

**Comment by kohlerdominik** [comment]
@endroid Looks like khanamiryan/php-qrcode-detector-decoder#103 just got merged 👍

Will you make a 3.x release with the fix?

**Comment by endroid** [comment]
@kohlerdominik nice, updated and tagged ;)
