### ISSUE TITLE
php8 imagecreatetruecolor returnType change 

### ISSUE THREAD

**Issue by Mexxim** [endroid/qr-code#294]
imagecreatetruecolor returns an GdImage Object instead of a resource 
PngWriter.php line 71 + 96

suggested fix:

`$image = @imagecreatetruecolor($data['block_count'] * $baseSize, $data['block_count'] * $baseSize)
                    or die("Unable to generate image: check your GD installation");`
    
remove:
`if (!is_resource($image)) {
   throw new GenerateImageException('Unable to generate image: check your GD installation');
}`

**Comment by endroid** [comment]
Hi @Mexxim thanks but all is_resource checks were already removed in december so this is not relevant anymore. A PHP 8 compatible release will be tagged as soon as [this pull request](https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/103) is merged. Thank you.

**Comment by acelaya** [comment]
Hey @endroid. That PR you reference seems to be completely innactive, and there are no real reasoning of why they don't merge it.

Would you consider looking for alternatives for this dependency to unblock this? Even a fork of `khanamiryan/php-qrcode-detector-decoder` published with a different name might be an option. You can always abandon it later when they eventually merge that and go back to the dependency as it is now.

**Comment by endroid** [comment]
Hi @acelaya as described in https://github.com/endroid/qr-code/issues/292 I will not create a tag with a forked version but you can still temporarily use the forked dependency by using the composer repositories section as desribed in that issue if you are in need of a PHP 8 compatible solution. Good luck.

**Comment by acelaya** [comment]
Nice! That should be enough.

I have already voted and commented in the original PR, same as others. I hope it becomes active again soon.

**Comment by endroid** [comment]
In the new 4.0.0 version which is PHP 8.0 compatible both resource and GdImage are supported.

**Comment by acelaya** [comment]
Thanks a lot @endroid 

I updated to v4.0 a few days ago, and it was flawless. Also, I love the new Builder approach.

Thanks for the hard work 💪🏼
