### ISSUE TITLE
Show QRcode

### ISSUE THREAD

**Issue by adailtonmoura** [endroid/qr-code#297]
In version 8 of php, the QR code does not appear, only a white square appears.

### Code 

```php
<?php

require __DIR__ . "/vendor/autoload.php";

use Endroid\QrCode\QrCode;

$qrCode = new QrCode('Life is too short to be generating QR codes');


header('Content-Type: '.$qrCode->getContentType());

echo $qrCode->writeString();

```
In version 7.4 this code work!!

### Image

![endroidtestphp8](https://user-images.githubusercontent.com/54925262/107108013-9d709300-6813-11eb-9810-26c72002cfe7.jpeg)

**Comment by chris97pl** [comment]
It's most likely related to PHP8 issue (GD required). See this and next comment:
https://www.php.net/manual/en/function.imagecreatetruecolor.php#125734

**Comment by endroid** [comment]
Hi @adailtonmoura if you uncomment the header line you can see the exact error message. Also the library has no PHP 8 support yet so I as mentioned above this will probably not work ;)

**Comment by endroid** [comment]
In the new 4.0.0 version which is PHP 8.0 compatible both resource and GdImage are supported.
