### ISSUE TITLE
Issue in Scanning Kanji QR code using camera in xamarin

### ISSUE THREAD

**Issue by vinukodi** [endroid/qr-code#298]
I have a problem in reading/scanning the kanji mode or double byte encoded QR codes. I have tried with setting character set to "Shift_JIS" and "SJIS" to read  the QR. But doesn't work. Can any one share me the reason and how to fix it.?

![image](https://user-images.githubusercontent.com/78755115/107264886-8e831e00-6a69-11eb-9f70-ecb1044e87ec.png)

**Comment by endroid** [comment]
Hi @vinukodi from here I can scan the code correctly using my Android scanner and I also see the image is generated correctly by my library so I think it is related to the reader. Still you could post your question in https://github.com/Bacon/BaconQrCode which provides the matrix for my library. The author knows more about the internals of how codes are generated and maybe he has some advice on how to make your code more readable.

**Comment by vinukodi** [comment]
> ows more about the internals of how codes are

When I run the app in debug mode the QR is get scanned, when I deploy the app in release mode the QR doesn't get scanned.
Below is the code snippet I use. Can you share me the working code snippet? if so it will be a great help to try out.

zxing.net.Mobile version 2.4.1

![image](https://user-images.githubusercontent.com/78755115/107373099-28030c00-6b0c-11eb-9c68-85f7a05733e5.png)

**Comment by endroid** [comment]
@vinukodi I scanned the image you included in your post using the QR & Barcode Scanner app from the play store, so unfortunately I have no code snippets to share ;)

**Comment by vinukodi** [comment]
> @vinukodi I scanned the image you included in your post using the QR & Barcode Scanner app from the play store, so unfortunately I have no code snippets to share ;)

QR app from the play store it works, the app which I have created, using the above code snippet it doesn't dork. so I'm looking for working code snippet.
