### ISSUE TITLE
Code don't run in CI4 latest version or PHP 8+

### ISSUE THREAD

**Issue by syferg** [endroid/qr-code#301]

**Comment by Yuii-guoguo** [comment]
Extension cannot work in php8.0, error: unable to generate image: check your GD installation

**Comment by endroid** [comment]
H @syferg and @Yuii-guoguo the 3.x version will not work in PHP 8 (awaiting compatibility of an extension). The new version (4.0.0) however is PHP 8 compatible as you can see [here](https://github.com/endroid/qr-code/runs/1996037176?check_suite_focus=true).

**Comment by syferg** [comment]
Thank you very much and sorry for not including the question 🙏
