### ISSUE TITLE
Invalid code in input string for cyrillic label

### ISSUE THREAD

**Issue by erkinsergey** [endroid/qr-code#303]
Hello!
An attempt to set a label in Russian gives an error: 
```
imagettfbbox(): any2eucjp(): invalid code in input string (2)
```
There are no mistakes in English. 
Also, there are no errors if you encode the text in Russian with UTF-8 encoding. The error only occurs with a label. 

```
$encodedText = 'Hello!';
$qrCode = new QrCode($encodedText);
$qrCode->setLabel('Текст на русском', 16, __DIR__ . '/../../vendor/endroid/qr-code/assets/fonts/noto_sans.otf');
```

**Comment by endroid** [comment]
Hi @erkinsergey unfortunately I can not reproduce the error on this end. If I Google the error message it appears to have something to do with your GD installation, see https://www.programmersought.com/article/80162245565/#_php___enablegdjisconv__13. Maybe you can try that or try the provided to_entities workaround and report back if that helped. Or you could try running in a different environment / PHP installation to rule this out.

Good luck!

**Comment by erkinsergey** [comment]
Thanks for the quick response!
Yes, I saw this article when I was looking for an answer. 
I really didn't get the error on another PHP installation. This is not your library's fault.
