### ISSUE TITLE
Feature request: vertical label alignment

### ISSUE THREAD

**Issue by MarekOtruba** [endroid/qr-code#307]
Hello,

would it be possible to add vertical label alignment?  We want use brand logo on the bottom and label for top of qr code. 
Are you planning to add this option/feature or not?

Marek

**Comment by endroid** [comment]
Hi @MarekOtruba unfortunately this is not a planned feature. This library will only provide one logo and label. I had to draw the line somewhere ;) You can find the current logic for writing a label here: https://github.com/endroid/qr-code/blob/master/src/Writer/PngWriter.php#L146. With some copying and tweaking I think it won't be too much work to add it to your code afterwards.

**Comment by MarekOtruba** [comment]
Hi, and what do you think about making writer's methods protected instead of private. After that, it could be possible to extend that classes and make minor changes.
