### ISSUE TITLE
https://endroid.nl/ is down.

### ISSUE THREAD

**Issue by NikoGrano** [endroid/qr-code#318]
Official site https://endroid.nl/ is down at this moment.

**Comment by endroid** [comment]
Hi @NikoGrano to be precise: it is not down but it has no content at the moment but thanks for noticing :) Were you looking for something specific?

**Comment by NikoGrano** [comment]
I was actually looking more detailed documentation. However, already figured it out by reading the code.

**Comment by camillo777** [comment]
Accessing now endroid.nl:

Fatal error: Uncaught RuntimeException: Unable to write in the "cache" directory (/var/www/html/symfony-start/var/cache/prod). in /var/www/html/symfony-start/vendor/symfony/http-kernel/Kernel.php:640 Stack trace: #0 /var/www/html/symfony-start/vendor/symfony/http-kernel/Kernel.php(544): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/html/symfony-start/vendor/symfony/http-kernel/Kernel.php(786): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/html/symfony-start/vendor/symfony/http-kernel/Kernel.php(187): Symfony\Component\HttpKernel\Kernel->preBoot() #3 /var/www/html/symfony-start/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 /var/www/html/symfony-start/vendor/autoload_runtime.php(35): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() #5 /var/www/html/symfony-start/public/index.php(5): require_once('/var/www/html/s...') #6 {main} thrown in /var/www/html/symfony-start/vendor/symfony/http-kernel/Kernel.php on line 640
