### ISSUE TITLE
Interface 'Endroid\QrCode\Builder\BuilderInterface' not found

### ISSUE THREAD

**Issue by lipphi31** [endroid/qr-code#320]
Hello,

I just download the endroid/qr-code.
For my web site, I use CodeIgniter 4 with PHP 7.3.5 under Apache 2.4.25.
I have pasted the endroid/qr-code on the Libraries folder with a subfolder Endroid.
Then, I call what I need with :
require_once('app\Libraries\Endroid\Builder\Builder.php');
require_once('app\Libraries\Endroid\ErrorCorrectionLevel\ErrorCorrectionLevelMedium.php');
require_once('app\Libraries\Endroid\Writer\PngWriter.php');

When I run it, the error appear.

For information, if I download it with composer, that work but my target is to use it without composer.

I don't see what's the problem.

I'm a really newbie in web coding then sorry...

Thanks a lot for the help in solving this problem,

**Comment by endroid** [comment]
Hi @lipphi31 the default and recommended way would indeed be installation via Composer but if that is not possible I think I would create a custom autoloader which - given a class name - loads the correct file so you don't have to manually require the files. You can find more information on creating your own autoloader [here](https://www.php.net/manual/en/language.oop5.autoload.php). Good luck!
