### ISSUE TITLE
Can't add logo in svg format

### ISSUE THREAD

**Issue by fullbl** [endroid/qr-code#321]
Hello, many thanks for this library!
I found a little problem: when trying to use a svg logo, it breaks at `src/ImageData/LogoImageData.php:55`, because imagecreatefromstring can't accept an svg image.
You can see it in some tests I wrote here: https://github.com/fullbl/qr-code/runs/2436730242

If needed, I would like to provide some help.
I think it's possible to get height and width directly from the xml attributes if the logo is in svg format, while keeping it like this if in another format. 

The problem comes when trying to write the qr code in png with the logo in svg, since $logoImageData->getImage() should return a GD resource, which doesn't support svg.

The solutions, in my opinion, can be one of those:

- if the writer is png, only png logo allowed
- use imagick instead of gd
- convert the logo in png (how?) when using it in png writer

What do you think about it?

**Comment by endroid** [comment]
Hi @fullbl thank you. At the moment only GD is supported and I have no plans for using Imagick so I think for now PNG writers should not write SVG logos and while SVG writers should. I will change the LogoImageData class so it supports both (this is a bug) and make sure proper exceptions are thrown in case of an unsupported format (also not properly handled at the moment).

**Comment by endroid** [comment]
I created a new release which throws a proper exception when the PNG writer receives a SVG logo and avoids trying to convert SVG logos to GD resources.

**Comment by fullbl** [comment]
Wow! So fast! Thank you!
