### ISSUE TITLE
LogoImageData::detectMimeTypeFromUrl returns array

### ISSUE THREAD

**Issue by breakerh** [endroid/qr-code#323]
The detectMimeTypeFromUrl function returns the content-type. However in some cases get_headers can return content-type as an array.

So maybe change return to:

```
return is_array($headers['Content-Type'])? $headers['Content-Type'][1] : $headers['Content-Type'];
```

Ps. `get_headers($url, 1);` Would be better so you will always get an array and select with `end()`

**Comment by endroid** [comment]
Hi @breakerh I added a workaround for this behavior in the latest patch. Thank you!
