### ISSUE TITLE
Corner radius for barcode data

### ISSUE THREAD

**Issue by UVLabs** [endroid/qr-code#331]
Is it possible to create barcodes with corner radius like this? 

<img width="654" alt="Screenshot 2021-06-24 at 11 30 59 AM" src="https://user-images.githubusercontent.com/10324144/123291253-f0579800-d4df-11eb-9ed0-7665cf17bbd2.png">

You can see this in action here: https://larsjung.de/jquery-qrcode/latest/demo/
https://larsjung.de/jquery-qrcode/

Other customization ideas can be seen here:

https://larsjung.de/jquery-qrcode/
https://larsjung.de/kjua/

**Comment by endroid** [comment]
Hi @UVLabs thank you for your suggestion. looks like a nice addition. I don't have the time to do this myself but I will mark this as an opportunity for contribution.

**Comment by syntaxgirl** [comment]
Hey @endroid, I would like to do this, also I would like to add possibility to change corner shape, to add an overlay if possible. What's the best place to start checking the code for such features to implement?

**Comment by endroid** [comment]
Hi @syntaxgirl you could create your own writer, like the ones created here https://github.com/endroid/qr-code/tree/master/src/Writer. As you can see in the PngWriter you can start by retrieving the matrix and then use that to build your drawing logic on. For the PNG writer this is a simple loop but for determining if you want round corners you probably want to check adjacent cells to determine if a corner should be rounded.

**Comment by endroid** [comment]
I'm closing this ticket because of lack of input. However if anyone still wants to add this feature, feel free to reopen / make a PR.
