### ISSUE TITLE
No read QR with logo

### ISSUE THREAD

**Issue by andrtechno** [endroid/qr-code#335]
http://prntscr.com/180es9p no logo

http://prntscr.com/180evpw with logo

**Comment by endroid** [comment]
Hi @andrtechno unfortunately when using a logo I can not guarantee readability. However, you can adjust the size, error correction level, logo size etc to make it more readable as described on https://github.com/endroid/qr-code#readability and you can use the [built-in validation reader](https://github.com/endroid/qr-code#built-in-validation-reader) to check if the QR code is at least readable by the library itself. However that does not guarantee any other reader (they are all somewhat different) will be able to read the QR code.

**Comment by andrtechno** [comment]
@endroid https://www.qrcode-monkey.com/ 
reads normally. generates different QR with and without logo

**Comment by andrtechno** [comment]
it generates QR outside the block with the logo, and you seem to overlap the top
