### ISSUE TITLE
SVG/EPS: Wrong output (white lines) when decimal separator is not point (locale LC_NUMERIC)

### ISSUE THREAD

**Issue by tvch** [endroid/qr-code#336]
Hello there

When i generating svg output in my (laravel-based) app the output is correct.
To optimize the the speed, I moved this part to a worker queue and there are now white lines in the generated output.

I created the following example of the bug:
```
#!/usr/bin/env php
<?php

use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\QrCode;

require __DIR__.'/../vendor/autoload.php';

$qrCode = new QrCode("payload");
$qrCode->setRoundBlockSize(false);
$qrCode->setErrorCorrectionLevel(ErrorCorrectionLevel::MEDIUM());
$qrCode->setEncoding('UTF-8');
$qrCode->setMargin(0);
$qrCode->setWriterByName('svg');

echo $qrCode->writeString();
```

<img width="1362" alt="sample" src="https://user-images.githubusercontent.com/5571012/125917036-82734132-2dc3-40fa-9dfd-8c4477af8460.png">

**Comment by tvch** [comment]
Has nobody an idea?

**Comment by tvch** [comment]
Hello there,

The problem is the numeric locale used when the svg (or eps*) output is created. I can fix it, with adding this line:

`setlocale( LC_NUMERIC, 'C' );  // Any locale where the decimal separator is a point`

My local locale is de_CH, which defaults to a comma as separator (if it's not set). My local server defaults to the local 'C'.

*The eps output is not valid, because all decimal pints are commas. 

Maybe someone can write a proper fix @endroid? 

Thanks Tobi

PS: I didn't notice that there was whole new version (v4). I did refactor my code to use newest version, but the problem is still there.

**Comment by endroid** [comment]
@tvch thank you for the pointer. I will see if I can fix this after my holiday.

**Comment by tvch** [comment]
Glad to help :) 

I changed the topic accordingly

**Comment by endroid** [comment]
Hi @tvch I now replaced the strval method with number_format in the SvgWriter and EpsWriter so the decimals are always formatted independent of the locale. Please note however that when you disable block size rounding, you can still see the lines between the blocks in case of an Svg because the renderer (browser) does not handle fractions very well.
