### ISSUE TITLE
Unbundle fonts

### ISSUE THREAD

**Issue by alecpl** [endroid/qr-code#341]
Distributing the package with a project release increases the size by ~15MB, which is a lot.

Please, consider moving fonts into a separate, optional package. All fonts, or only the OTF.

**Comment by endroid** [comment]
Hi @alecpl thank you for your input. I will not remove the font but if you can provide a much smaller compatible font I will be happy to replace it. See #103 and #224.

**Comment by alecpl** [comment]
I fail to see where the OTF font is used/required in the code.

**Comment by endroid** [comment]
Here you can see it is the default font https://www.github.com/endroid/qr-code/tree/master/src%2FLabel%2FLabel.php

**Comment by alecpl** [comment]
For those not needing a text on QR-code a solution is to use `bacon/bacon-qr-code` directly.
