### ISSUE TITLE
Invalid data at path...

### ISSUE THREAD

**Issue by pipovich16** [endroid/qr-code#343]
Hi, i'm using qrCode in symfony 5 and  i have this exception (Invalid data at path...) when execute $result = $writer->write($qrCode, $logo, $label). I think can't create png file. Any idea?

Thanks!

**Comment by erufenix** [comment]
Any solution?

**Comment by stefanobusinarolo** [comment]
Hi , I had the same problem and the reason was the $logo parameter.
As a first step try without logo and without label with $result = $writer->write ($qrCode, NULL, NULL);
