### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Ulyssesyi** [endroid/qr-code#347]
LogoImageData::detectMimeTypeFromUrl throw type error because some code error.
```php
 $format = PHP_VERSION > 80000 ? true : 1;
```
PHP_VERSION is string, try to use as integer so the expression always is false. And at next line  the "get_headers" function need arg#2 be bool, but $format is 1. So it will throw type error in strict_types
@endroid

**Comment by endroid** [comment]
Hi @Ulyssesyi thank you. I updated the code so it uses the version_compare method.

**Comment by Ulyssesyi** [comment]
@endroid version_compare can't use php version id as argument. The second argument should be '8.0.0' not '80000'. It should be PHP_VERSION_ID >= 80000 ? true : 1 or version_compare(PHP_VERSION, '8.0.0') >=0 ? true : 1

**Comment by endroid** [comment]
Ah didn't see that one, thought I was working with ID already ;) Fixed, thank you!
