### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by Twenty4marc** [endroid/qr-code#348]
Any screenshots?

**Comment by endroid** [comment]
![Screenshot_20210914-214453.jpg](https://user-images.githubusercontent.com/537253/133323626-8d9283a1-2eda-4747-ba33-2864cdd11521.jpg)

**Comment by endroid** [comment]
Or did you mean something else ;)

**Comment by Twenty4marc** [comment]
Haha 😂 
I mean screenshots from your app :)

**Comment by endroid** [comment]
😄 Here is an example. It is nothing more than a QR code. The version with the image is just an overlay (no other effects) and an optional label can be added underneath the QR code (you can specify the font / size / colors yourself)
![example](https://user-images.githubusercontent.com/537253/133579437-efb2daf7-0ea2-4132-8430-10f9023d1619.png)
