### ISSUE TITLE
Can't use logo with background 

### ISSUE THREAD

**Issue by gitchak** [endroid/qr-code#351]
When I add a logo with a background some of the data on the QR code is hidden hence the QR code is not working.

Here are the same QR code with and without logo

https://new-bucket-490412fa.s3.eu-west-1.amazonaws.com/google_nologo.png
https://new-bucket-490412fa.s3.eu-west-1.amazonaws.com/google.png

Please help me solve this. Your code is superb.

**Comment by endroid** [comment]
Hi @gitchak indeed adding a logo makes your code less readable so I advise to tweak the size, error correction level etc and use the validator to make sure it is readable. See [this issue](https://github.com/endroid/qr-code/issues/335) or read the readme for more information. Good luck!
