### ISSUE TITLE
Execution time out 120 seconds

### ISSUE THREAD

**Issue by sayandeepmajumdar** [endroid/qr-code#356]
I'm using the builder method to generate QR codes.  Now my count of QR codes is around 1000s. 
Normally I'm running it on my localhost & getting a timeout error. 

So could you please tell me for printing more than 1000 QR codes what should we use?  so that I can't get the timeout error. 

(Yes I can increase time limit, but without this how I can do that)

**Comment by endroid** [comment]
Hi @sayandeepmajumdar if generation takes more than 120s on your side and you need a solution without changing the time limit I think you have to split up your work in workloads. A clean solution would be creating a message queue with workloads and let one or multiple consumers (PHP processes) handle these until all are processed.
