### ISSUE TITLE
Minimum PHP version not specified

### ISSUE THREAD

**Issue by andrewroazen** [endroid/qr-code#357]
There are still a number of PHP 5.x installations out there, it would be helpful if the documentation mentioned its dependency on =>7.0.0. I too hope some day this won't be necessary any more.

`PHP Warning:  Unsupported declare 'strict_types' in /path/to/script/qr-code/tests/QrCodeTest.php on line 3`
`PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /path/to/script/cgi-bin/qr-code/tests/QrCodeTest.php on line 41`

**Comment by sprain** [comment]
The supported php versions are visible in the `composer.json` file:
https://github.com/endroid/qr-code/blob/master/composer.json
