### ISSUE TITLE
runs normally when on windows, but error when on linux

### ISSUE THREAD

**Issue by bayuik** [endroid/qr-code#358]
![qrcode](https://user-images.githubusercontent.com/58217016/142357036-36516a16-a55e-4e57-a2dd-be9c6720f138.PNG)

**Comment by endroid** [comment]
Hi @bayuik if you use composer to manage your dependencies and include the autoloader provided by composer you should be ready to go ;) See https://getcomposer.org/doc/01-basic-usage.md for more information on proper autoloading. Good luck!
