### ISSUE TITLE
4.4.3 update made QR codes too bold

### ISSUE THREAD

**Issue by daniser** [endroid/qr-code#360]
My config:
```php
$qrCode = QrCode::create($this->data)
    ->setEncoding(new Encoding('UTF-8'))
    ->setErrorCorrectionLevel(new ErrorCorrectionLevelHigh)
    ->setSize(100)
    ->setMargin(10)
    ->setRoundBlockSizeMode(new RoundBlockSizeModeMargin)
    ->setForegroundColor(new Color(0, 0, 0))
    ->setBackgroundColor(new Color(255, 255, 255, 127));

return (new PngWriter)->write($qrCode);
```

Result (4.4.2):
![image](https://user-images.githubusercontent.com/5169543/145815481-cbbcc2ea-9a18-45e5-af18-a7423a3091b8.png)

Result (4.4.3):
![image](https://user-images.githubusercontent.com/5169543/145815656-1cd9998e-4a06-4513-ba7e-a74e3281e86a.png)

While iPhone X recognizes first QR code "on the fly", it struggles with the second one.

**Comment by endroid** [comment]
Hi @daniser thank you. I looked into it and it appeared there was something wrong with the offsets. This should be fixed in 4.4.6.
