### ISSUE TITLE
Add support for PHP 8.x

### ISSUE THREAD

**Issue by PhoenixBWS** [endroid/qr-code#362]
When run on PHP 8.0 or PHP 8.1, it causes a Fatal Error. Please add support for PHP 8.1.

**Comment by endroid** [comment]
Hi @PhoenixBWS I am running it under PHP 8.1 and am not getting any errors. Also, all checks under PHP 8.x are successful, see https://github.com/endroid/qr-code/actions/runs/1660408990. What version do you have installed and what is the error message?

**Comment by PhoenixBWS** [comment]
@endroid It throws the following error:
**Fatal error**: Uncaught RuntimeException: Index invalid or out of range in <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/MaskUtil.php:106 Stack trace: #0 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(181): BaconQrCode\Encoder\MaskUtil::applyMaskPenaltyRule3() #1 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(228): BaconQrCode\Encoder\Encoder::calculateMaskPenalty() #2 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(119): BaconQrCode\Encoder\Encoder::chooseMaskPattern() #3 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/endroid/qr-code/src/Bacon/MatrixFactory.php(18): BaconQrCode\Encoder\Encoder::encode() #4 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/endroid/qr-code/src/Writer/PngWriter.php(29): Endroid\QrCode\Bacon\MatrixFactory->create() #5 <LONG_PATH_TO_DIRECTORY>/public_html/components/generator.php(27): Endroid\QrCode\Writer\PngWriter->write() #6 <LONG_PATH_TO_DIRECTORY>/public_html/index.php(27): include('...') #7 {main} thrown in <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/MaskUtil.php on line 106

**Comment by PhoenixBWS** [comment]
In _composer.json_, I see the version listed there is:

`"endroid/qr-code": "^4.4"`

**Comment by endroid** [comment]
And what bacon qr code library version do you have in your lock file? As it appears to be some issue in that code.

**Comment by PhoenixBWS** [comment]
Yes, it looks like that. By the way, the Bacon QR Code library version looks like below in my _composer.lock_

`"name": "bacon/bacon-qr-code",
"version": "2.0.4"`

I also found an [https://github.com/Bacon/BaconQrCode/issues/92](issue there) but that was not resolved yet.

**Comment by endroid** [comment]
Ah that must be it then. Hope it will be resolved soon.

**Comment by endroid** [comment]
@PhoenixBWS As I mentioned all my tests are running successfully under PHP 8.x and with bacon qr code lib 2.0.4 so I think the error only occurs for specific use cases which are not covered by the tests. If you can provide a failing test case (or complete code fragment that results in the issue) I can see if I can reproduce the issue and we can use that information to help the author of the library which has the bug to reproduce and solve it.
