### ISSUE TITLE
I cant use label

### ISSUE THREAD

**Issue by harryngne** [endroid/qr-code#363]
My code:

if($note != "")
 $qrcode->setLabel(&note, 16,'public/fonts/open_sans.ttf', LabelAlignment::CENTER());

Pleae help me use it

**Comment by endroid** [comment]
Hi @harryngne the readme describes usage of labels extensively: either with or without builder. What version of the library are you using? There is no setLabel in the latest version. It should be something like the code below. Good luck!

```
$qrCode = QrCode::create('Data')
    ->setEncoding(new Encoding('UTF-8'))
    ....
$label = Label::create($note);
$result = $writer->write($qrCode, null, $label);
```
