### ISSUE TITLE
login coinbase with my  email /wakangaia27@gmail.com not getting sms 2 verification

### ISSUE THREAD

**Issue by FerryBTC** [endroid/qr-code#374]
login coinbase with my  email /wakangaia27@gmail.com not getting sms 2 verification 

__Originally posted by @FerryBTC in https://github.com/coinbase/code-of-conduct/issues/2#issuecomment-1123155479__

**Comment by endroid** [comment]
Hello @FerryBTC this library does not provide any sms verification.
