### ISSUE TITLE
Default  margin if use ErrorCorrectionLevelLow

### ISSUE THREAD

**Issue by kib-ev** [endroid/qr-code#377]
When use errorCorrectionLevel = ErrorCorrectionLevelLow result png has default margin = about 10 even if set margin = 0
When use errorCorrectionLevel = ErrorCorrectionLevelHigh result png has default margin = 0 if set margin = 0

$result = Builder::create()
                ->writer(new PngWriter())
                ->writerOptions([])
                ->data($user->getAdGuid())
                ->encoding(new Encoding('UTF-8'))
                ->errorCorrectionLevel(new ErrorCorrectionLevelLow())
                ->size(300)
                ->margin(0)
                ->roundBlockSizeMode(new RoundBlockSizeModeMargin())
                ->labelText(now()->format('d.m.Y H:i'))
                ->labelFont(new NotoSans(16))
                ->labelAlignment(new LabelAlignmentCenter())
                ->build();

**Comment by endroid** [comment]
Hi @kib-ev maybe this is related to the roundBlockSizeMode: the one you selected (margin) instructs the renderer to round block sizes to whole numbers (for sharpness) and use a margin if the number of blocks * block size is smaller than the desired image size. You can try using the RoundBlockSizeNone() mode, maybe this solves your issue.

Good luck!
