### ISSUE TITLE
Document status of `validateResult`

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/qr-code#385]
There was a change regarding the validator in 4.0.0, but the current status quo is not documented in README. Some questions (if you give me answers, I'll come up with a PR):
1. Is there *any* validation available for SVG?
2. Is `khanamiryan/php-qrcode-detector-decoder` still supported at all? Without it, the internal validator is used? So which advantage does this additional package bring? Does it have to be configured/enabled, or is it enough to install it?
3. Does this apply to the internal validator or to `khanamiryan` (quoted from https://github.com/endroid/qr-code#built-in-validation-reader):
    > Take note that the validator can consume quite amount of additional resources and it should be installed separately only if you use it.

**Comment by endroid** [comment]
Hi @ThomasLandauer the khanamiryan validator is currently the only validator and it only works for the PngWriter. When you try to enable validation for a writer that does not support validation or don't have the validator installed you will get a proper error message so the developer implementing the package will be pointed in the right direction.

**Comment by ThomasLandauer** [comment]
Well, this is the message I'm getting - not too much help I would say ;-)
> An exception has been thrown during the rendering of a template ("Unable to validate result with Endroid\QrCode\Writer\SvgWriter")

Anyway, after thinking some more about this, I'm starting to question the validation in total: What happens if it does fail? Some exception probably? So enabling this in PROD environment probably isn't the best idea, cause the end user would get a blank page?!

**Comment by endroid** [comment]
I agree the message could be a bit clearer, I will make it more descriptive. However the point is that the developer gets the necessary feedback during development before it goes to production. And what happens on prod is up to the developer and depends on the use case: you can choose to catch the exception and do something with it (i.e. show an error page or regenerate using other parameters) or you can still continue to use the result, even though it failed.
