### ISSUE TITLE
Fix for the issue when there are some spaces (paddings) between blocks (pixels)

### ISSUE THREAD

**Issue by mrself** [endroid/qr-code#390]
After generating an SVG QR code I noticed one issue when resizing the code in the browser:

![image](https://user-images.githubusercontent.com/9679597/201440153-935f9a45-8054-47a0-82a0-64fb2e150348.png)

As you can see, there are some spaces. I spend some time trying to understand why this happened, but no luck. This bug (?) was there don't matter what I was doing.

So, my solution is quite interesting: I counted the blocks count on the code. There were 37 blocks. Then I multiplied it by 10 and had 370px. I am not sure how it worked. I am not even sure if there was really 37 blocks. But it works perfectly now. It does not matter how small / big my SVG is, there are no spaces now.

Just decided to post it here in case.

**Comment by endroid** [comment]
@mrself Thank you, hope this helps anyone having the same issue.
