### ISSUE TITLE
Replacement for writeDataUri

### ISSUE THREAD

**Issue by matthiez** [endroid/qr-code#394]
Hi,
my current task is to upgrade old code and some artifacts refer to $qrCode->->writeDataUri(). What is the equivalent in newer versions? I couldn't find anything in the releases history.

Thanks for helping!
André

**Comment by endroid** [comment]
Hi @matthiez in the new version you can create a result and call `getDataUri()` on it as described here: https://github.com/endroid/qr-code#usage-working-with-results. Good luck!
