### ISSUE TITLE
If it is encrypted by sourceGuardian14, it cannot run

### ISSUE THREAD

**Issue by 284099857** [endroid/qr-code#397]
My PHP environment is 73. If my code uses your package, it will open an error message after using sourceGuardian14 encryption. The error message is Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 1131573536 bytes)

**Comment by endroid** [comment]
Hi @284099857 I am not familiar with sourceGuardian14 encryption nor do I have any idea how it has any impact on how the library works so unfortunately I am not able to help you. Memory usage is mostly dependent on things like image size and error correction level, maybe you can find some settings that work in your setup if sourceGuardian14 causes such a memory load. Good luck! If you find a solution, please report back as it might also help other users encountering the same issue.
