### ISSUE TITLE
Runtime Exception: Index Invalid or Out of Range during QR Code Generation

### ISSUE THREAD

**Issue by ketantupple** [endroid/qr-code#408]
I encountered a runtime exception with the error message "index invalid or out of range" while attempting to generate a QR code. I am seeking assistance in resolving this issue.

![image_2023_05_31T04_38_20_722Z](https://github.com/endroid/qr-code/assets/135096787/cc19239b-75d1-4276-9bc2-236c1cca8084)

**Comment by endroid** [comment]
Duplicate of
https://github.com/endroid/qr-code/issues/362
https://github.com/endroid/qr-code/issues/365
https://github.com/endroid/qr-code/issues/396

See https://github.com/Bacon/BaconQrCode/issues/92 for further information
