### ISSUE TITLE
[Feature Request] Shape and edge styles

### ISSUE THREAD

**Issue by potatowski** [endroid/qr-code#410]
Create a new customizable to QR Code to shape style

Examples:
![image](https://github.com/endroid/qr-code/assets/65042811/c0e0f81d-5aa1-4c2e-9c86-865bd1f550d5)

**Comment by TEGDEOMBALLA** [comment]
Is it possible to have a QR code in a circular shape with the Endroid\qr-code library?

**Comment by ruby232** [comment]
Customize the SvgWriter class to create a custom SVG in case it helps someone.
[Gist custom SvgWriter](https://gist.github.com/ruby232/18c80d61b281d35ac8903e4c768226eb)
