### ISSUE TITLE
Outputting png without loggo produces messed up image source text instead of actual image string

### ISSUE THREAD

**Issue by verybigelephants** [endroid/qr-code#414]
I have this simple testing code:

```
		$qr = QrCode::create("test");
		$writer = new PngWriter();
		$result = $writer->write($qr);
		header('Content-Type: '.$result->getMimeType());
		echo $result->getString();
```

and instead of the image the browser outputs
```
�PNG  IHDR@@B�2� pHYs���+IDATx���An�@A+����< /��:I����|~~~���?�7�?C��!L�&`0� �a�0C��!L��}����3zw؝9����s��ov�>��&`0� �a�0C��!L�&`0� �a��H����21=31�s��������a�0C��!L�&`0� �a�0C��!��i�s�;r�t9w�,�k�KN`0� �a�0C��!L�&`0� �a���i�7��_���}sK�qC��!L�&`0� �a�0C��!L�&`0��Fڱ�ˇk8�!L�&` ... 
```

however, when i add some random dummy logo like
`$logo = Logo::create(public_path('test.png'))->setResizeToWidth(50)->setPunchoutBackground(true);` 
and output it via 
`$writer->write($qr, $logo);`
i do get an actual image

**Comment by endroid** [comment]
Hi @verybigelephants that's strange. It looks like the content-type header is not set correctly. Are you sure you have no other logic that touches your response headers? What is the output of your $result->getMimeType() and what Content-Type header string do you see in your browser?

**Comment by verybigelephants** [comment]
hello, thank you for the quick response!

the getMimeType() outputs `image/png` 

iam pretty sure there is no other output before the code, as i have these 2 code-blocks (one with builder, one with QrCode::create), and while i use the Builder one it outputs without logo correctly, but when i uncomment the codeblock with the QrCode::create i get the messed up output, here are the full contents of my method in a testing controller:


```
	public function test(Request $request){
		/* 
		//method 1
		$qr = QrCode::create("test");
		$writer = new PngWriter();
		$result = $writer->write($qr);
		header('Content-Type: '.$result->getMimeType());
		echo $result->getString();
		/**/
		
		/*
		//method 2
		$result = Builder::create()
			->writer(new PngWriter())
			->writerOptions([])
			->data('Custom QR code contents')
			->encoding(new Encoding('UTF-8'))
			->errorCorrectionLevel(new ErrorCorrectionLevelHigh())
			->size(800)
			->margin(10)
			->roundBlockSizeMode(new RoundBlockSizeModeMargin())
			->validateResult(false)
			->build();
			
			
		header('Content-Type: '.$result->getMimeType());
		echo $result->getString();
		/**/
	}
```

**Comment by verybigelephants** [comment]
try it yourself, just copypaste the code in any controller: i can't figure out which part of `//method 1` generation does something that the browser always gets `Content-Type:
text/html; charset=UTF-8` instead of `header('Content-Type: '.$result->getMimeType());`, even when i write `header('Content-Type: image/png');` like this below:

i even tried doing it like this
```
		$qr = QrCode::create("test");
		$writer = new PngWriter();
		$result = $writer->write($qr);
		header('Content-Type: image/png');
		echo $result->getString();
```


commenting out exactly this block and using the second block instead works, so there is no other output

**Comment by JanSlabon** [comment]
JM2C: Wouldn't it make sense to set the content-type and result into your `Response` object (I guess there's such) instead of echoing and sending the header in your controller method?

**Comment by endroid** [comment]
@verybigelephants I did paste the code block but on my side I don't get any unexpected results or incorrect headers.
@JanSlabon that would be better indeed. The Symfony bundle provides a QrCodeResponse for this purpose.

**Comment by verybigelephants** [comment]
don't get me wrong, i can create a functional qr code with the `Builder` method provided in the exapmle, and of course, building a manual response header like this worked
```
		$response = Response::make($result->getString());
		$response->header('Content-Type', $result->getMimeType());
		return $response;
```

i was trying to report that there is something buggy/fishy going on when doing it without a logo like this 
```
		$qr = QrCode::create("test");
		$writer = new PngWriter();
		$result = $writer->write($qr);
		header('Content-Type: '.$result->getMimeType());
		echo $result->getString();
```
because when i either 1) use the method 2 (with the same `header`/`echo`) or 2) replace line `$result = $writer->write($qr);` with `$writer->write($qrCode, $logo);` **it does work** as expected and sets the correct header, which would suggest that when the library is calling writer->write($qr) without the `$logo` parameter it in it maybe throws something/echoes some parameter undefined warning under the hood

**Comment by JanSlabon** [comment]
If you work with a framework that handels requests and responses for you, just use them. Any echo or header call will bypass the framework or will end in an output-buffer... it's not clean to work against the request/response concept. I guess that the framework simply "overwrites" the header() with its default header. The difference between a raw qr code and a qr code with an image could be that the one with the image will end in a bigger result, that flushes the output-buffer and is immediately send to the client while the one without a logo will not get flushed and the framework response logic takes place.

In any case you should check your error reporting and logs for details.

**Comment by verybigelephants** [comment]
of course i've checked and there's no errors/logs

and as i mentioned, the headers are correct when i either use the logo with method 1 **or** use the builder when no logo is included, so it's not gonna be framework overwriting header with default one because of the content size. 

anyways, from the comments i guess there is no clear way to find out what is the library doing with method 1 that forces laravel to overwrite the headers so i think we can close it

**Comment by endroid** [comment]
Just trying to help but I cannot reproduce it on this side with the examples you provided, so it's just guessing from here. Still, if you find the cause and it is a bug in this library, please let me know and I will create a corresponding test case and fix it. Good luck!
