### ISSUE TITLE
Specifying QR code models

### ISSUE THREAD

**Issue by gilbertfl** [endroid/qr-code#419]
This really is a question and not an issue.

I am currently implementing the QR code printing function for my fork of escpos-tools:  [gilbertfl/escpos-netprinter](https://github.com/gilbertfl/escpos-netprinter).    The ESC/pos printing protocol necessitates that a "QR model" be specified, but I cannot find how to convey the selected model to the Builder::create() chain.

ESC/pos handles QR Model 1, QR Model 2 and Micro-QR code.
Here is the spec on those models: https://www.qrcode.com/en/codes/model12.html

Does this library support specifying the model type?  If so, how do I do it?

**Comment by endroid** [comment]
Hi @gilbertfl this library does not provide such models. I hope you find a library that does, good luck!

**Comment by gilbertfl** [comment]
ZXing seems to manage specifying the model, so I will look at it's diverse descendents (other than BaconQR) to see if I find something that works for me.

Thanks for the quick reply!
