### ISSUE TITLE
Problems using library

### ISSUE THREAD

**Issue by forcecodema** [endroid/qr-code#422]
There is a problem using qr-code library.

After installing the library with composer, and following the instructions on github repo page (using with/without builder), there is an error with loading ErrorCorrectionLevel class. Same story with RoundBlockSizeMode class...

Directory structure in vendor/endroid/qr-code/src directory looks different than the src in github repo. There are ErrorCorrectionLevel and RoundBlockSizeMode directories in vendor/endroid/qr-code/src, which do not exists in github repo...

**Comment by endroid** [comment]
Hi @forcecodema those classes where specifically updated during the last release, see https://github.com/endroid/qr-code/releases so I think you are working with an older (<5.x) version. In that case you can either upgrade to the new version or use the specific error correction level classes available in that version. See the old docs https://github.com/endroid/qr-code/blob/61675912115d1f543179f4239f25d9f9f5c48c50/README.md
