### ISSUE TITLE
imagettfbbox(): Could not find/open font

### ISSUE THREAD

**Issue by LeQuangKhai99** [endroid/qr-code#423]
I have error 
![image](https://github.com/endroid/qr-code/assets/55009300/4d6240de-f69c-4155-ba87-455b9219d36d)
![image](https://github.com/endroid/qr-code/assets/55009300/b4f6f04b-b09a-400d-9bba-cea948972bde)
It error when i add label. It seems like it can't read the default font file

**Comment by endroid** [comment]
Hi @LeQuangKhai99 what version are you using? The current version checks if the path to the font exists (this happens in Label::create) while the imagettfbbox method is called later, when writing the image. So it appears that the font does exist but it can't be opened. Please put a debug statement in the LoadImageData class just before the imagettfbbox method and tell me what `$label->getFont()->getPath()` resolves to and what `file_exists($label->getFont()->getPath())` resolves to.

**Comment by LeQuangKhai99** [comment]
Hi @endroid, file_exists($label->getFont()->getPath()) return true.

**Comment by LeQuangKhai99** [comment]
![image](https://github.com/endroid/qr-code/assets/55009300/b6f7539d-5d4e-4b8b-b30b-5e6498682e61)

noto_sans.oft is exist

**Comment by endroid** [comment]
Thank you. And the output of the path please.

**Comment by LeQuangKhai99** [comment]
@endroid I'm sorry, i was installed this package to another project and it work well. I think i will uninstall and try again. Thanks!

**Comment by endroid** [comment]
Np, glad to hear your problem is solved!
