### ISSUE TITLE
PArameter documentation

### ISSUE THREAD

**Issue by B0rner** [endroid/qr-code#426]
Hey,

in the `readme.md` there is an example, how to use the class, like this: 

> $result = Builder::create()
>     ->writer(new PngWriter())
>     ->writerOptions([])
>     ->data('Custom QR code contents')
>     ->encoding(new Encoding('UTF-8'))
>     ->errorCorrectionLevel(ErrorCorrectionLevel::High)
>     ->size(300)
>     ->margin(10)
>     ->roundBlockSizeMode(RoundBlockSizeMode::Margin)
>     ->logoPath(__DIR__.'/assets/symfony.png')
>     ->logoResizeToWidth(50)
>     ->logoPunchoutBackground(true)
>     ->labelText('This is the label')
>     ->labelFont(new NotoSans(20))
>     ->labelAlignment(LabelAlignment::Center)
>     ->validateResult(false)
>     ->build();

But I can't found any documentation about the valid parameters.

For example: `errorCorrectionLevel(ErrorCorrectionLevel::High)` What are the possible values?
Or what does `300`stands for in ` ->size(300)`? px? pt?  em? I use size 300 with base64 output, but the image isshow very large. Maybe scaled by the browser maybe generated in >300px

Are there any alternative parameters for `  ->roundBlockSizeMode(RoundBlockSizeMode::Margin)`??

Is there a detailed documentation for all the parameters, also for the writer, etc.?

**Comment by endroid** [comment]
Hi @B0rner you can find the valid ErrorCorrectionLevel values in the enum and your IDE will suggest the available values when developing, the size is generally in pixels and the RoundBlockSizeMode values can be found in the enum and are documented at https://github.com/endroid/qr-code#round-block-size-mode. Good luck!

**Comment by B0rner** [comment]
Thank you for answering that question so fast.
