### ISSUE TITLE
Background color and margin for logo

### ISSUE THREAD

**Issue by billdagou** [endroid/qr-code#427]
Hi Jeroen,

Is it possible to provide the abilities to set the bg color and the margin for logo?

Thanks.

**Comment by endroid** [comment]
Hi @billdagou yes that is possible. The readme at https://github.com/endroid/qr-code describes how you can set the bg color and margin via the builder or directly via the QrCode class. Good luck!

**Comment by endroid** [comment]
@billdagou for the logo unfortunately this is not possible. That functionality will purely be kept to adding an image in-place as-is so if you need that you would need to add some pre-processing yourself or make sure the logo already has the correct margin or background color. You could use the `$result->getMatrix()` for this purpose to do the necessary calculations.
