### ISSUE TITLE
how to set the version of a qrcode

### ISSUE THREAD

**Issue by youpuyewolong** [endroid/qr-code#435]
the version of a QR code indicates its size, data storage capacity, and potential error correction capabilities, with versions ranging from 1 to 40

so how to set the version

**Comment by endroid** [comment]
Hi @youpuyewolong my library does not support such versions, only error correction levels. You can look at the underlying library which generates the QR code matrix https://github.com/Bacon/BaconQrCode if such functionality is available. If so, maybe this can be implemented. Good luck and thank you for your question.
