### ISSUE TITLE
Call to undefined method Endroid\QrCode\QrCode::create()

### ISSUE THREAD

**Issue by musiquero** [endroid/qr-code#439]
It may be something very simple, but I've been busting my head and can't find the solution. I did the installation with composer, but it always gives me an error with the imported method. I have tried with the code as it appears here at the beginning and as it appears in the YT video. But the result is always the same.

Call to undefined method Endroid\QrCode\QrCode::create()

PHP Fatal error:  Uncaught Error: Class "Endroid\QrCode\Builder\Builder" not found in /...

**Comment by endroid** [comment]
Hi @musiquero what version do you have installed according to you composer.lock file? And if you go to the QrCode class can you find a create method or what do you see?

**Comment by hallosatria347** [comment]
i experienced the same problem.
you can see in my screenshot that the PngWriter class is not read.
<img width="579" alt="errorr" src="https://github.com/endroid/qr-code/assets/94790639/3e03d2be-326a-4aaa-80c0-da638c792861">

sorry if my language is not good. I used Google Translate and I hope you understand.
thanks.

**Comment by endroid** [comment]
Hi @hallosatria347 the same question for you: what version do you have installed according to your composer.lock file? Also you can check the vendor/endroid/qr-code folder and see if the class `PngWriter` exists in the `Endroid\QrCode\Writer` namespace. If so, your autoloading is broken.
