### ISSUE TITLE
[Feature Request] SvgWriter with choice of code generation policy - Option to Use Previous SVG Generation Method with <defs>

### ISSUE THREAD

**Issue by kojot-kk** [endroid/qr-code#443]
Hello,

I've been benefiting from your library and appreciate the efficiency it offers. I've noticed the recent shift from using the <defs> block to direct element embedding within SVGs.

The <defs> method used before significantly aids in modifying the code, thanks to its organized structure that simplifies post-generation edits.

Could you consider offering the previous <defs> based generation as an optional policy?

Thank you for your work on this library and for considering this suggestion to enhance its adaptability and usefulness.

Best,

Krzysztof

**Comment by endroid** [comment]
Hi @kojot-kk in 5.0.9 you can now pass an option `SvgWriter::WRITER_OPTION_COMPACT => false` to disable compact SVG generation and fall back to XML block definitions. Good luck!

**Comment by kojot-kk** [comment]
Thanks a lot!

**Comment by sdespont** [comment]
@endroid Thank you very much for the option ! Because for some reasons, including an SVG QR-Code compacted (with `<path>`) in a [TCPDF ](https://github.com/tecnickcom/TCPDF) document increase a lot the file size !

**Comment by endroid** [comment]
Thank you!
