### ISSUE TITLE
Composer install problem

### ISSUE THREAD

**Issue by fafayqa** [endroid/qr-code#448]
I am trying to install this php library using Composer FOR THE FIRST TIME EVER but whatever I try it always give an error: `Unable to launch a new process`.

I am using kind of "manual install trick" shown [HERE](https://stackoverflow.com/a/48319499/19018243) as I do not have option running custom install scripts on a live server, I can only manually upload files.

So I did exactly step-by-step what was required, yet I did not move a bit as it immediately throws at me abovementioned error in a big red square in CMD window as soon as I run CMD command `php composer.phar update` (as required).

I am on Win10 x64 using USBWebserver with PHP 8.1 and have all the file access privilegues.

**Comment by endroid** [comment]
Hi @fafayqa any progress on this issue? Looks like you're missing some resources like maybe RAM, CPU or storage space (which are resources necessary to create a process) or maybe your web server has some other restrictions. However I am unfamiliar with the internals of both USBWebserver and Composer so I can't give you the answer. Hope you will find the cause though, good luck!
