### ISSUE TITLE
Use QR code in an <img> tag

### ISSUE THREAD

**Issue by Whip** [endroid/qr-code#450]
Sorry for the dumb question but can you post a basic example of how I can put the generated qr code in an html img tag without saving an image/svg file?

**Comment by endroid** [comment]
Hi @Whip if you want to embed the QR code without generating a file you can use the `$result->getDataUri();` method as described in the readme to generate a data URI and pass that to you img `src` attribute. Good luck!

**Comment by Whip** [comment]
My bad. I didn't spot that. Much thanks
