### ISSUE TITLE
support generating dot style qrcode-s

### ISSUE THREAD

**Issue by pentium10** [endroid/qr-code#451]
Add option to support modern dot style qrcode.

![image](https://github.com/user-attachments/assets/c18f7fbf-c5de-4b02-96d2-33af9dc41913)

**Comment by ruby232** [comment]
Customize the SvgWriter class to create a custom SVG in case it helps someone.
[Gist custom SvgWriter](https://gist.github.com/ruby232/18c80d61b281d35ac8903e4c768226eb)

**Comment by endroid** [comment]
@ruby232 thank you for your input. This library will not add different dot styles.
