### ISSUE TITLE
QR code scanner

### ISSUE THREAD

**Issue by emmasmith1001** [endroid/qr-code#453]
It's really amazing tool. but I am looking to design a tool like [qr code scanner](https://qrcodescaner.us/) which can help me to scan qr code too. I am paying for this if you are interested.

**Comment by OscarWilde** [comment]
There is already another Project, doing this via JS: https://github.com/mebjas/html5-qrcode

**Comment by endroid** [comment]
Hi @emmasmith1001 my library uses the khanamiryan/qrcode-detector-decoder library to read and validate QR codes but something like @OscarWilde (the great writer) suggests might also be suitable depending on your needs. It will not be a part of this library which will remain limited to representing QR codes.
