### ISSUE TITLE
Call to undefined method Endroid\QrCode\Builder\Builder::create()

### ISSUE THREAD

**Issue by Saad-Ramzan-Kiani** [endroid/qr-code#457]
I'm trying to make Qr Code of links provided by user, 

Method: if (isset($validatedData['Permit_link'])) {

                $qrCodeImage = Builder::create()
                    ->writer(new PngWriter())
                    ->data($validatedData['Permit_link'])
                    ->size(300)
                    ->build();
            
                    $fileName = 'QrCode_' . time() . '.png';
                    $directory = 'uploads/qrcode_images';

                Storage::disk('public')->put($directory . '/' . $fileName, $qrCodeImage->getString());

                $validatedData['Permit_qr_link'] = $directory . '/' . $fileName;
            }

its working perfectly on localhost but on liver server, its displaying me this error: "Internal Server Error: Call to undefined method Endroid\QrCode\Builder\Builder::create() "

**Comment by endroid** [comment]
Hi @Saad-Ramzan-Kiani what version are you using to your composer.lock file?

**Comment by Saad-Ramzan-Kiani** [comment]
"require": {
        "php": "^8.2",
        "endroid/qr-code": "^5.0.7",

**Comment by endroid** [comment]
@Saad-Ramzan-Kiani this is the requirement, what does your lock file say? Also, please look at the Builder.php file on the server and let me know what it shows.

**Comment by Saad-Ramzan-Kiani** [comment]
my composer.lock file: ""name": "endroid/qr-code",
            "version": "5.0.7",
            "source": {
                "type": "git",
                "url": "https://github.com/endroid/qr-code.git",
                "reference": "0cc00f0626b73bc71a1ea17af01387d0ac75e046"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/endroid/qr-code/zipball/0cc00f0626b73bc71a1ea17af01387d0ac75e046",
                "reference": "0cc00f0626b73bc71a1ea17af01387d0ac75e046",
                "shasum": ""
            },
            "require": {
                "bacon/bacon-qr-code": "^2.0.5",
                "php": "^8.1"
            },
            "conflict": {
                "khanamiryan/qrcode-detector-decoder": "^1.0.6"
            },
            "require-dev": {
                "endroid/quality": "dev-main",
                "ext-gd": "*",
                "khanamiryan/qrcode-detector-decoder": "^1.0.4||^2.0.2",
                "setasign/fpdf": "^1.8.2"
            },
            "suggest": {
                "ext-gd": "Enables you to write PNG images",
                "khanamiryan/qrcode-detector-decoder": "Enables you to use the image validator",
                "roave/security-advisories": "Makes sure package versions with known security issues are not installed",
                "setasign/fpdf": "Enables you to use the PDF writer"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "5.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Endroid\\QrCode\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Jeroen van den Enden",
                    "email": "info@endroid.nl"
                }
            ],
            "description": "Endroid QR Code",
            "homepage": "https://github.com/endroid/qr-code",
            "keywords": [
                "code",
                "endroid",
                "php",
                "qr",
                "qrcode"
            ],
            "support": {
                "issues": "https://github.com/endroid/qr-code/issues",
                "source": "https://github.com/endroid/qr-code/tree/5.0.7"
            },
            "funding": [
                {
                    "url": "https://github.com/endroid",
                    "type": "github"
                }
            ],
            "time": "2024-03-08T11:24:40+00:00"
        },"

**Comment by endroid** [comment]
Your lock looks fine, that version should have the create method, see https://github.com/endroid/qr-code/blob/0cc00f0626b73bc71a1ea17af01387d0ac75e046/src/Builder/Builder.php#L72. In other words, the remote server seems to have a different version than the one according to your lock file. Please check what methods your live server's Builder.php.

Make sure to check on the live server, not locally of course ;)

**Comment by Saad-Ramzan-Kiani** [comment]
For version: 6.0.0, what method is used in place of create() to generate a new QR code?

**Comment by endroid** [comment]
In 6.x you can simply use the constructor, see https://github.com/endroid/qr-code/blob/master/README.md

**Comment by Saad-Ramzan-Kiani** [comment]
to update to latest version :"endroid/qr-code": "^6.0.1",
code: " composer update endroid/qr-code --with-all-dependencies "

Please mention it in README.md file.

**Comment by Saad-Ramzan-Kiani** [comment]
I updated to the latest version, then revised my method, and now it's working perfectly.

**Comment by melroy89** [comment]
> constructor

Can you please add this to your release notes?? https://github.com/endroid/qr-code/releases

I mean I need to debug on my local server. Trying to find the issue in github issues. In order to know how to upgrade from v5 to v6
