### ISSUE TITLE
Ambiguity on builder vs non-builder

### ISSUE THREAD

**Issue by designosis** [endroid/qr-code#458]
What are the cost/benefits of the builder method vs the non-builder method?

**Comment by endroid** [comment]
Hi @designosis good question. When you have one single location where you generate the QR code you don't need the builder. A builder is useful when you want to abstract or centralize the QR code, logo and label configuration (or even multiple configurations via multiple builders) and reuse those elsewhere in other parts of your application without bothering about the internals there. Hope it's clear now, good luck!
