### ISSUE TITLE
i cant include the logo with the QR code

### ISSUE THREAD

**Issue by SaadKiani-5** [endroid/qr-code#461]
my code for generating and storing qrcode: "
use Endroid\QrCode\Builder\Builder;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelHigh;
use Endroid\QrCode\Label\Alignment\LabelAlignmentCenter;
use Endroid\QrCode\Label\Font\OpenSans;
use Endroid\QrCode\RoundBlockSizeMode\RoundBlockSizeModeMargin;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Label\Alignment\Logo;
// use Endroid\QrCode\Logo\Logo;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Storage;

public function store(Request $request)
{
    $request->validate([
        'url' => 'required|url',
        'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
    ]);

    // Handle logo upload
    $logoPath = $request->hasFile('image')
        ? $request->file('image')->store('uploads/logos', 'public')
        : null;

    // Generate unique filenames
    $qrCodeFilename = 'qrcodes/' . uniqid() . '.png';
    $pdfFilename = 'qrcodes/' . uniqid() . '.pdf';

    // Build the QR Code
    $builder = Builder::create()
        ->writer(new PngWriter())
        ->writerOptions([])
        ->data($request->input('url'))
        ->encoding(new Encoding('UTF-8'))
        ->errorCorrectionLevel(new ErrorCorrectionLevel(ErrorCorrectionLevel::HIGH))
        ->size(300)
        ->margin(10)
        ->roundBlockSizeMode(new RoundBlockSizeModeMargin());

    // Add logo if uploaded
    if ($logoPath) {
        $fullLogoPath = storage_path('app/public/' . $logoPath);
        $builder->logoPath($fullLogoPath)
                ->logoResizeToWidth(50)
                ->logoPunchoutBackground(true);
    }

    // Optional label
    $builder->labelText('Custom Label')
            ->labelFont(new OpenSans(16))
            ->labelAlignment(new LabelAlignmentCenter());

    // Build the QR Code
    $result = $builder->build();

    // Save the QR Code
    $qrCodeContent = $result->getString();
    Storage::disk('public')->put($qrCodeFilename, $qrCodeContent);

    // Generate PDF
    $pdf = PDF::loadHTML('<img src="' . asset('storage/' . $qrCodeFilename) . '" />')
        ->save(storage_path('app/public/' . $pdfFilename));

    // Save to database
    QrCodeGenerate::create([
        'image_path' => $logoPath ? str_replace('public/', '', $logoPath) : null,
        'qr_path' => $qrCodeFilename,
        'pdf_path' => $pdfFilename,
        'url' => $request->input('url'),
    ]);

    // Redirect to the show method with QR code details
    return redirect()->route('qrcode.show', [
        'qr_path' => $qrCodeFilename,
        'pdf_path' => $pdfFilename,
    ]);
}"

**Comment by endroid** [comment]
Hi @SaadKiani-5 what do you get when you dump the $logoPath variable. Or try putting a dump statement or breakpoint within the `if ($logoPath) {` block. Also you can dump the $builder just before you create the result to see if the logo options are set correctly. Please let me know what output you get on those locations.
